namespace AsBuiltExplorer
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
    this.components = (IContainer) new System.ComponentModel.Container();
    ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (Form1));
    this.TabControl1 = new TabControl();
    this.TabPage1 = new TabPage();
    this.chkCompareShowNames = new CheckBox();
    this.lblComp4VIN = new Label();
    this.lblComp3VIN = new Label();
    this.lblComp2VIN = new Label();
    this.lblComp1VIN = new Label();
    this.Button9 = new Button();
    this.tbxCompFile4 = new TextBox();
    this.Label23 = new Label();
    this.Button7 = new Button();
    this.tbxCompFile3 = new TextBox();
    this.Label22 = new Label();
    this.chkCompareShowChecksum = new CheckBox();
    this.btnCompLoad = new Button();
    this.btnCompBrowse2 = new Button();
    this.btnCompBrowse1 = new Button();
    this.tbxCompFile2 = new TextBox();
    this.tbxCompFile1 = new TextBox();
    this.ListView1 = new ListView();
    this.ColumnHeader1 = new ColumnHeader();
    this.ColumnHeader2 = new ColumnHeader();
    this.ColumnHeader3 = new ColumnHeader();
    this.ColumnHeader4 = new ColumnHeader();
    this.ColumnHeader5 = new ColumnHeader();
    this.ColumnHeader6 = new ColumnHeader();
    this.ColumnHeader7 = new ColumnHeader();
    this.ColumnHeader8 = new ColumnHeader();
    this.ColumnHeader9 = new ColumnHeader();
    this.ContextMenuStrip1 = new ContextMenuStrip(this.components);
    this.CopyToolStripMenuItem = new ToolStripMenuItem();
    this.EntireLineToolStripMenuItem = new ToolStripMenuItem();
    this.Data1hexToolStripMenuItem = new ToolStripMenuItem();
    this.Data2hexToolStripMenuItem = new ToolStripMenuItem();
    this.Data3hexToolStripMenuItem = new ToolStripMenuItem();
    this.BinaryToolStripMenuItem = new ToolStripMenuItem();
    this.ExportModuleToolStripMenuItem = new ToolStripMenuItem();
    this.ToUCDSToolStripMenuItem = new ToolStripMenuItem();
    this.ToABTToolStripMenuItem = new ToolStripMenuItem();
    this.Label7 = new Label();
    this.Label6 = new Label();
    this.TabPage2 = new TabPage();
    this.TextBox5 = new TextBox();
    this.Button3 = new Button();
    this.Button2 = new Button();
    this.Label16 = new Label();
    this.Label15 = new Label();
    this.tbxChecksumBin = new TextBox();
    this.tbxConvertBin = new TextBox();
    this.tbxConvertHex = new TextBox();
    this.tbxData3bin2 = new TextBox();
    this.tbxData2bin2 = new TextBox();
    this.tbxData1bin2 = new TextBox();
    this.tbxData3bin1 = new TextBox();
    this.tbxData2bin1 = new TextBox();
    this.tbxData1bin1 = new TextBox();
    this.tbxChecksumHex = new TextBox();
    this.Label5 = new Label();
    this.Button1 = new Button();
    this.tbxData3hex = new TextBox();
    this.Label4 = new Label();
    this.tbxData2hex = new TextBox();
    this.Label3 = new Label();
    this.tbxData1hex = new TextBox();
    this.Label2 = new Label();
    this.tbxModIDhex = new TextBox();
    this.Label1 = new Label();
    this.TabPage3 = new TabPage();
    this.TextBox2 = new TextBox();
    this.Label12 = new Label();
    this.Label9 = new Label();
    this.chkDeduceDownloadAB = new CheckBox();
    this.btnDeduceSaveInfo = new Button();
    this.wbDeducer = new WebBrowser();
    this.btnDeduceOpenETIS = new Button();
    this.TabPage4 = new TabPage();
    this.chkDeduceDoCCC = new CheckBox();
    this.Button8 = new Button();
    this.Label14 = new Label();
    this.TextBox1 = new TextBox();
    this.Label13 = new Label();
    this.Label11 = new Label();
    this.Label10 = new Label();
    this.lstDeduceYears = new CheckedListBox();
    this.lstDeduceModels = new CheckedListBox();
    this.tbxDeduceReport = new TextBox();
    this.btnDeduceFigureIt = new Button();
    this.btnDeduceLoadOptions = new Button();
    this.lstDeduceFactoryOptions = new ListBox();
    this.TabPage5 = new TabPage();
    this.Button10 = new Button();
    this.TextBox4 = new TextBox();
    this.Label21 = new Label();
    this.lstBit_Modules = new ListBox();
    this.Button6 = new Button();
    this.Button5 = new Button();
    this.Label20 = new Label();
    this.Label19 = new Label();
    this.lstBit_Years = new CheckedListBox();
    this.lstBit_Models = new CheckedListBox();
    this.Label17 = new Label();
    this.TextBox3 = new TextBox();
    this.Label18 = new Label();
    this.tbxDeduceReport2 = new TextBox();
    this.Button4 = new Button();
    this.TabPage6 = new TabPage();
    this.btnBrowseRefresh = new Button();
    this.lvwBrowser = new ListView();
    this.ColumnHeader10 = new ColumnHeader();
    this.ColumnHeader11 = new ColumnHeader();
    this.ColumnHeader12 = new ColumnHeader();
    this.ColumnHeader13 = new ColumnHeader();
    this.ColumnHeader14 = new ColumnHeader();
    this.ContextMenuStrip2 = new ContextMenuStrip(this.components);
    this.SetAsCompare1ToolStripMenuItem = new ToolStripMenuItem();
    this.SetAsCompare2ToolStripMenuItem = new ToolStripMenuItem();
    this.SetAsCompare3ToolStripMenuItem = new ToolStripMenuItem();
    this.SetAsCompare4ToolStripMenuItem = new ToolStripMenuItem();
    this.ToolStripMenuItem1 = new ToolStripSeparator();
    this.DeleteFileToolStripMenuItem = new ToolStripMenuItem();
    this.Label8 = new Label();
    this.PictureBox1 = new PictureBox();
    this.chkShowOnlyMismatches = new CheckBox();
    this.TextBox6 = new TextBox();
    this.TabControl1.SuspendLayout();
    this.TabPage1.SuspendLayout();
    this.ContextMenuStrip1.SuspendLayout();
    this.TabPage2.SuspendLayout();
    this.TabPage3.SuspendLayout();
    this.TabPage4.SuspendLayout();
    this.TabPage5.SuspendLayout();
    this.TabPage6.SuspendLayout();
    this.ContextMenuStrip2.SuspendLayout();
    ((ISupportInitialize) this.PictureBox1).BeginInit();
    this.SuspendLayout();
    this.TabControl1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
    this.TabControl1.Controls.Add((Control) this.TabPage1);
    this.TabControl1.Controls.Add((Control) this.TabPage2);
    this.TabControl1.Controls.Add((Control) this.TabPage3);
    this.TabControl1.Controls.Add((Control) this.TabPage4);
    this.TabControl1.Controls.Add((Control) this.TabPage5);
    this.TabControl1.Controls.Add((Control) this.TabPage6);
    this.TabControl1.Location = new Point(16 /*0x10*/, 15);
    this.TabControl1.Margin = new Padding(4);
    this.TabControl1.Name = "TabControl1";
    this.TabControl1.SelectedIndex = 0;
    this.TabControl1.Size = new Size(999, 591);
    this.TabControl1.TabIndex = 0;
    this.TabPage1.BackColor = SystemColors.Control;
    this.TabPage1.Controls.Add((Control) this.chkShowOnlyMismatches);
    this.TabPage1.Controls.Add((Control) this.chkCompareShowNames);
    this.TabPage1.Controls.Add((Control) this.lblComp4VIN);
    this.TabPage1.Controls.Add((Control) this.lblComp3VIN);
    this.TabPage1.Controls.Add((Control) this.lblComp2VIN);
    this.TabPage1.Controls.Add((Control) this.lblComp1VIN);
    this.TabPage1.Controls.Add((Control) this.Button9);
    this.TabPage1.Controls.Add((Control) this.tbxCompFile4);
    this.TabPage1.Controls.Add((Control) this.Label23);
    this.TabPage1.Controls.Add((Control) this.Button7);
    this.TabPage1.Controls.Add((Control) this.tbxCompFile3);
    this.TabPage1.Controls.Add((Control) this.Label22);
    this.TabPage1.Controls.Add((Control) this.chkCompareShowChecksum);
    this.TabPage1.Controls.Add((Control) this.btnCompLoad);
    this.TabPage1.Controls.Add((Control) this.btnCompBrowse2);
    this.TabPage1.Controls.Add((Control) this.btnCompBrowse1);
    this.TabPage1.Controls.Add((Control) this.tbxCompFile2);
    this.TabPage1.Controls.Add((Control) this.tbxCompFile1);
    this.TabPage1.Controls.Add((Control) this.ListView1);
    this.TabPage1.Controls.Add((Control) this.Label7);
    this.TabPage1.Controls.Add((Control) this.Label6);
    this.TabPage1.Location = new Point(4, 25);
    this.TabPage1.Margin = new Padding(4);
    this.TabPage1.Name = "TabPage1";
    this.TabPage1.Padding = new Padding(4);
    this.TabPage1.Size = new Size(991, 562);
    this.TabPage1.TabIndex = 0;
    this.TabPage1.Text = "Compare As-Built";
    this.chkCompareShowNames.AutoSize = true;
    this.chkCompareShowNames.Checked = true;
    this.chkCompareShowNames.CheckState = CheckState.Checked;
    this.chkCompareShowNames.Location = new Point(167, 180);
    this.chkCompareShowNames.Name = "chkCompareShowNames";
    this.chkCompareShowNames.Size = new Size(154, 20);
    this.chkCompareShowNames.TabIndex = 19;
    this.chkCompareShowNames.Text = "Show Module Names";
    this.chkCompareShowNames.UseVisualStyleBackColor = true;
    this.lblComp4VIN.AutoSize = true;
    this.lblComp4VIN.ForeColor = Color.SaddleBrown;
    this.lblComp4VIN.Location = new Point(642, 116);
    this.lblComp4VIN.Name = "lblComp4VIN";
    this.lblComp4VIN.Size = new Size(50, 16 /*0x10*/);
    this.lblComp4VIN.TabIndex = 18;
    this.lblComp4VIN.Text = "[no file]";
    this.lblComp3VIN.AutoSize = true;
    this.lblComp3VIN.ForeColor = Color.BlueViolet;
    this.lblComp3VIN.Location = new Point(642, 85);
    this.lblComp3VIN.Name = "lblComp3VIN";
    this.lblComp3VIN.Size = new Size(50, 16 /*0x10*/);
    this.lblComp3VIN.TabIndex = 17;
    this.lblComp3VIN.Text = "[no file]";
    this.lblComp2VIN.AutoSize = true;
    this.lblComp2VIN.ForeColor = Color.DarkGreen;
    this.lblComp2VIN.Location = new Point(642, 54);
    this.lblComp2VIN.Name = "lblComp2VIN";
    this.lblComp2VIN.Size = new Size(50, 16 /*0x10*/);
    this.lblComp2VIN.TabIndex = 16 /*0x10*/;
    this.lblComp2VIN.Text = "[no file]";
    this.lblComp1VIN.AutoSize = true;
    this.lblComp1VIN.ForeColor = Color.Blue;
    this.lblComp1VIN.Location = new Point(642, 23);
    this.lblComp1VIN.Name = "lblComp1VIN";
    this.lblComp1VIN.Size = new Size(50, 16 /*0x10*/);
    this.lblComp1VIN.TabIndex = 15;
    this.lblComp1VIN.Text = "[no file]";
    this.Button9.Location = new Point(538, 112 /*0x70*/);
    this.Button9.Name = "Button9";
    this.Button9.Size = new Size(98, 27);
    this.Button9.TabIndex = 14;
    this.Button9.Text = "Browse...";
    this.Button9.UseVisualStyleBackColor = true;
    this.tbxCompFile4.ForeColor = Color.SaddleBrown;
    this.tbxCompFile4.Location = new Point(167, 113);
    this.tbxCompFile4.Name = "tbxCompFile4";
    this.tbxCompFile4.Size = new Size(343, 22);
    this.tbxCompFile4.TabIndex = 13;
    this.Label23.AutoSize = true;
    this.Label23.ForeColor = Color.SaddleBrown;
    this.Label23.Location = new Point(24, 116);
    this.Label23.Name = "Label23";
    this.Label23.Size = new Size(100, 16 /*0x10*/);
    this.Label23.TabIndex = 12;
    this.Label23.Text = "As-Built File # 4:";
    this.Button7.Location = new Point(538, 81);
    this.Button7.Name = "Button7";
    this.Button7.Size = new Size(98, 27);
    this.Button7.TabIndex = 11;
    this.Button7.Text = "Browse...";
    this.Button7.UseVisualStyleBackColor = true;
    this.tbxCompFile3.ForeColor = Color.BlueViolet;
    this.tbxCompFile3.Location = new Point(167, 82);
    this.tbxCompFile3.Name = "tbxCompFile3";
    this.tbxCompFile3.Size = new Size(343, 22);
    this.tbxCompFile3.TabIndex = 10;
    this.Label22.AutoSize = true;
    this.Label22.ForeColor = Color.BlueViolet;
    this.Label22.Location = new Point(24, 85);
    this.Label22.Name = "Label22";
    this.Label22.Size = new Size(100, 16 /*0x10*/);
    this.Label22.TabIndex = 9;
    this.Label22.Text = "As-Built File # 3:";
    this.chkCompareShowChecksum.AutoSize = true;
    this.chkCompareShowChecksum.Location = new Point(167, 154);
    this.chkCompareShowChecksum.Name = "chkCompareShowChecksum";
    this.chkCompareShowChecksum.Size = new Size(159, 20);
    this.chkCompareShowChecksum.TabIndex = 8;
    this.chkCompareShowChecksum.Text = "Include Checksum bits";
    this.chkCompareShowChecksum.UseVisualStyleBackColor = true;
    this.btnCompLoad.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.btnCompLoad.Location = new Point(523, 145);
    this.btnCompLoad.Name = "btnCompLoad";
    this.btnCompLoad.Size = new Size(113, 59);
    this.btnCompLoad.TabIndex = 7;
    this.btnCompLoad.Text = "Load Files";
    this.btnCompLoad.UseVisualStyleBackColor = true;
    this.btnCompBrowse2.Location = new Point(538, 50);
    this.btnCompBrowse2.Name = "btnCompBrowse2";
    this.btnCompBrowse2.Size = new Size(98, 27);
    this.btnCompBrowse2.TabIndex = 6;
    this.btnCompBrowse2.Text = "Browse...";
    this.btnCompBrowse2.UseVisualStyleBackColor = true;
    this.btnCompBrowse1.Location = new Point(538, 19);
    this.btnCompBrowse1.Name = "btnCompBrowse1";
    this.btnCompBrowse1.Size = new Size(98, 27);
    this.btnCompBrowse1.TabIndex = 5;
    this.btnCompBrowse1.Text = "Browse...";
    this.btnCompBrowse1.UseVisualStyleBackColor = true;
    this.tbxCompFile2.ForeColor = Color.DarkGreen;
    this.tbxCompFile2.Location = new Point(167, 51);
    this.tbxCompFile2.Name = "tbxCompFile2";
    this.tbxCompFile2.Size = new Size(343, 22);
    this.tbxCompFile2.TabIndex = 4;
    this.tbxCompFile1.ForeColor = Color.Blue;
    this.tbxCompFile1.Location = new Point(167, 20);
    this.tbxCompFile1.Name = "tbxCompFile1";
    this.tbxCompFile1.Size = new Size(343, 22);
    this.tbxCompFile1.TabIndex = 3;
    this.ListView1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
    this.ListView1.Columns.AddRange(new ColumnHeader[9]
    {
      this.ColumnHeader1,
      this.ColumnHeader2,
      this.ColumnHeader3,
      this.ColumnHeader4,
      this.ColumnHeader5,
      this.ColumnHeader6,
      this.ColumnHeader7,
      this.ColumnHeader8,
      this.ColumnHeader9
    });
    this.ListView1.ContextMenuStrip = this.ContextMenuStrip1;
    this.ListView1.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.ListView1.FullRowSelect = true;
    this.ListView1.HideSelection = false;
    this.ListView1.Location = new Point(17, 243);
    this.ListView1.Name = "ListView1";
    this.ListView1.Size = new Size(956, 297);
    this.ListView1.TabIndex = 2;
    this.ListView1.UseCompatibleStateImageBehavior = false;
    this.ListView1.View = View.Details;
    this.ColumnHeader1.Text = "Module Address";
    this.ColumnHeader1.Width = 128 /*0x80*/;
    this.ColumnHeader2.Text = "Data1";
    this.ColumnHeader2.Width = 81;
    this.ColumnHeader3.Text = "Data2";
    this.ColumnHeader3.Width = 87;
    this.ColumnHeader4.Text = "Data3";
    this.ColumnHeader4.Width = 92;
    this.ColumnHeader5.Text = "Same?";
    this.ColumnHeader5.Width = 76;
    this.ColumnHeader6.Text = "Binary";
    this.ColumnHeader6.Width = 473;
    this.ColumnHeader7.Text = "PartNumber";
    this.ColumnHeader8.Text = "Strategy";
    this.ColumnHeader8.Width = 158;
    this.ColumnHeader9.Text = "Calibration";
    this.ColumnHeader9.Width = 158;
    this.ContextMenuStrip1.ImageScalingSize = new Size(20, 20);
    this.ContextMenuStrip1.Items.AddRange(new ToolStripItem[2]
    {
      (ToolStripItem) this.CopyToolStripMenuItem,
      (ToolStripItem) this.ExportModuleToolStripMenuItem
    });
    this.ContextMenuStrip1.Name = "ContextMenuStrip1";
    this.ContextMenuStrip1.Size = new Size(181, 70);
    this.CopyToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[5]
    {
      (ToolStripItem) this.EntireLineToolStripMenuItem,
      (ToolStripItem) this.Data1hexToolStripMenuItem,
      (ToolStripItem) this.Data2hexToolStripMenuItem,
      (ToolStripItem) this.Data3hexToolStripMenuItem,
      (ToolStripItem) this.BinaryToolStripMenuItem
    });
    this.CopyToolStripMenuItem.Name = "CopyToolStripMenuItem";
    this.CopyToolStripMenuItem.Size = new Size(151, 22);
    this.CopyToolStripMenuItem.Text = "Copy";
    this.EntireLineToolStripMenuItem.Name = "EntireLineToolStripMenuItem";
    this.EntireLineToolStripMenuItem.Size = new Size(180, 22);
    this.EntireLineToolStripMenuItem.Text = "Entire Line";
    this.Data1hexToolStripMenuItem.Name = "Data1hexToolStripMenuItem";
    this.Data1hexToolStripMenuItem.Size = new Size(180, 22);
    this.Data1hexToolStripMenuItem.Text = "Data 1 (hex)";
    this.Data2hexToolStripMenuItem.Name = "Data2hexToolStripMenuItem";
    this.Data2hexToolStripMenuItem.Size = new Size(180, 22);
    this.Data2hexToolStripMenuItem.Text = "Data 2 (hex)";
    this.Data3hexToolStripMenuItem.Name = "Data3hexToolStripMenuItem";
    this.Data3hexToolStripMenuItem.Size = new Size(180, 22);
    this.Data3hexToolStripMenuItem.Text = "Data 3 (hex)";
    this.BinaryToolStripMenuItem.Name = "BinaryToolStripMenuItem";
    this.BinaryToolStripMenuItem.Size = new Size(180, 22);
    this.BinaryToolStripMenuItem.Text = "Binary";
    this.ExportModuleToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[2]
    {
      (ToolStripItem) this.ToUCDSToolStripMenuItem,
      (ToolStripItem) this.ToABTToolStripMenuItem
    });
    this.ExportModuleToolStripMenuItem.Name = "ExportModuleToolStripMenuItem";
    this.ExportModuleToolStripMenuItem.Size = new Size(180, 22);
    this.ExportModuleToolStripMenuItem.Text = "Export Module";
    this.ToUCDSToolStripMenuItem.Name = "ToUCDSToolStripMenuItem";
    this.ToUCDSToolStripMenuItem.Size = new Size(180, 22);
    this.ToUCDSToolStripMenuItem.Text = "To UCDS...";
    this.ToABTToolStripMenuItem.Name = "ToABTToolStripMenuItem";
    this.ToABTToolStripMenuItem.Size = new Size(180, 22);
    this.ToABTToolStripMenuItem.Text = "To ABT...";
    this.Label7.AutoSize = true;
    this.Label7.ForeColor = Color.DarkGreen;
    this.Label7.Location = new Point(24, 54);
    this.Label7.Name = "Label7";
    this.Label7.Size = new Size(100, 16 /*0x10*/);
    this.Label7.TabIndex = 1;
    this.Label7.Text = "As-Built File # 2:";
    this.Label6.AutoSize = true;
    this.Label6.ForeColor = Color.Blue;
    this.Label6.Location = new Point(24, 23);
    this.Label6.Name = "Label6";
    this.Label6.Size = new Size(100, 16 /*0x10*/);
    this.Label6.TabIndex = 0;
    this.Label6.Text = "As-Built File # 1:";
    this.TabPage2.BackColor = SystemColors.Control;
    this.TabPage2.Controls.Add((Control) this.TextBox5);
    this.TabPage2.Controls.Add((Control) this.Button3);
    this.TabPage2.Controls.Add((Control) this.Button2);
    this.TabPage2.Controls.Add((Control) this.Label16);
    this.TabPage2.Controls.Add((Control) this.Label15);
    this.TabPage2.Controls.Add((Control) this.tbxChecksumBin);
    this.TabPage2.Controls.Add((Control) this.tbxConvertBin);
    this.TabPage2.Controls.Add((Control) this.tbxConvertHex);
    this.TabPage2.Controls.Add((Control) this.tbxData3bin2);
    this.TabPage2.Controls.Add((Control) this.tbxData2bin2);
    this.TabPage2.Controls.Add((Control) this.tbxData1bin2);
    this.TabPage2.Controls.Add((Control) this.tbxData3bin1);
    this.TabPage2.Controls.Add((Control) this.tbxData2bin1);
    this.TabPage2.Controls.Add((Control) this.tbxData1bin1);
    this.TabPage2.Controls.Add((Control) this.tbxChecksumHex);
    this.TabPage2.Controls.Add((Control) this.Label5);
    this.TabPage2.Controls.Add((Control) this.Button1);
    this.TabPage2.Controls.Add((Control) this.tbxData3hex);
    this.TabPage2.Controls.Add((Control) this.Label4);
    this.TabPage2.Controls.Add((Control) this.tbxData2hex);
    this.TabPage2.Controls.Add((Control) this.Label3);
    this.TabPage2.Controls.Add((Control) this.tbxData1hex);
    this.TabPage2.Controls.Add((Control) this.Label2);
    this.TabPage2.Controls.Add((Control) this.tbxModIDhex);
    this.TabPage2.Controls.Add((Control) this.Label1);
    this.TabPage2.Location = new Point(4, 22);
    this.TabPage2.Margin = new Padding(4);
    this.TabPage2.Name = "TabPage2";
    this.TabPage2.Padding = new Padding(4);
    this.TabPage2.Size = new Size(991, 472);
    this.TabPage2.TabIndex = 1;
    this.TabPage2.Text = "Checksum Calc";
    this.TextBox5.BackColor = SystemColors.Info;
    this.TextBox5.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.TextBox5.Location = new Point(485, 22);
    this.TextBox5.Multiline = true;
    this.TextBox5.Name = "TextBox5";
    this.TextBox5.Size = new Size(173, 215);
    this.TextBox5.TabIndex = 24;
    this.TextBox5.Text = "This is just a checksum calculator.  Entire your module data (including the checksum).  \r\n\r\nClick Re-Calc, and a new checksum will be provided below.";
    this.Button3.Location = new Point(86, 408);
    this.Button3.Name = "Button3";
    this.Button3.Size = new Size(100, 27);
    this.Button3.TabIndex = 23;
    this.Button3.Text = "Bin to Hex";
    this.Button3.UseVisualStyleBackColor = true;
    this.Button2.Location = new Point(86, 319);
    this.Button2.Name = "Button2";
    this.Button2.Size = new Size(100, 27);
    this.Button2.TabIndex = 22;
    this.Button2.Text = "Hex to Bin";
    this.Button2.UseVisualStyleBackColor = true;
    this.Label16.AutoSize = true;
    this.Label16.Location = new Point(33, 383);
    this.Label16.Name = "Label16";
    this.Label16.Size = new Size(29, 16 /*0x10*/);
    this.Label16.TabIndex = 21;
    this.Label16.Text = "Bin:";
    this.Label15.AutoSize = true;
    this.Label15.Location = new Point(33, 355);
    this.Label15.Name = "Label15";
    this.Label15.Size = new Size(34, 16 /*0x10*/);
    this.Label15.TabIndex = 20;
    this.Label15.Text = "Hex:";
    this.tbxChecksumBin.BackColor = SystemColors.Control;
    this.tbxChecksumBin.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxChecksumBin.Location = new Point(280, 219);
    this.tbxChecksumBin.Margin = new Padding(4);
    this.tbxChecksumBin.MaxLength = 8;
    this.tbxChecksumBin.Name = "tbxChecksumBin";
    this.tbxChecksumBin.Size = new Size(89, 22);
    this.tbxChecksumBin.TabIndex = 19;
    this.tbxChecksumBin.Text = "00011111";
    this.tbxConvertBin.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxConvertBin.Location = new Point(86, 380);
    this.tbxConvertBin.Name = "tbxConvertBin";
    this.tbxConvertBin.Size = new Size(170, 22);
    this.tbxConvertBin.TabIndex = 18;
    this.tbxConvertHex.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxConvertHex.Location = new Point(86, 352);
    this.tbxConvertHex.Name = "tbxConvertHex";
    this.tbxConvertHex.Size = new Size(100, 22);
    this.tbxConvertHex.TabIndex = 17;
    this.tbxData3bin2.BackColor = SystemColors.Control;
    this.tbxData3bin2.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData3bin2.Location = new Point(326, 117);
    this.tbxData3bin2.Margin = new Padding(4);
    this.tbxData3bin2.MaxLength = 8;
    this.tbxData3bin2.Name = "tbxData3bin2";
    this.tbxData3bin2.Size = new Size(89, 22);
    this.tbxData3bin2.TabIndex = 16 /*0x10*/;
    this.tbxData3bin2.Text = "00011111";
    this.tbxData2bin2.BackColor = SystemColors.Control;
    this.tbxData2bin2.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData2bin2.Location = new Point(326, 85);
    this.tbxData2bin2.Margin = new Padding(4);
    this.tbxData2bin2.MaxLength = 8;
    this.tbxData2bin2.Name = "tbxData2bin2";
    this.tbxData2bin2.Size = new Size(89, 22);
    this.tbxData2bin2.TabIndex = 15;
    this.tbxData2bin2.Text = "11110000";
    this.tbxData1bin2.BackColor = SystemColors.Control;
    this.tbxData1bin2.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData1bin2.Location = new Point(326, 53);
    this.tbxData1bin2.Margin = new Padding(4);
    this.tbxData1bin2.MaxLength = 8;
    this.tbxData1bin2.Name = "tbxData1bin2";
    this.tbxData1bin2.Size = new Size(89, 22);
    this.tbxData1bin2.TabIndex = 14;
    this.tbxData1bin2.Text = "11111100";
    this.tbxData3bin1.BackColor = SystemColors.Control;
    this.tbxData3bin1.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData3bin1.Location = new Point(229, 117);
    this.tbxData3bin1.Margin = new Padding(4);
    this.tbxData3bin1.MaxLength = 8;
    this.tbxData3bin1.Name = "tbxData3bin1";
    this.tbxData3bin1.Size = new Size(89, 22);
    this.tbxData3bin1.TabIndex = 13;
    this.tbxData3bin1.Text = "00111111";
    this.tbxData2bin1.BackColor = SystemColors.Control;
    this.tbxData2bin1.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData2bin1.Location = new Point(229, 85);
    this.tbxData2bin1.Margin = new Padding(4);
    this.tbxData2bin1.MaxLength = 8;
    this.tbxData2bin1.Name = "tbxData2bin1";
    this.tbxData2bin1.Size = new Size(89, 22);
    this.tbxData2bin1.TabIndex = 12;
    this.tbxData2bin1.Text = "01000000";
    this.tbxData1bin1.BackColor = SystemColors.Control;
    this.tbxData1bin1.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData1bin1.Location = new Point(229, 53);
    this.tbxData1bin1.Margin = new Padding(4);
    this.tbxData1bin1.MaxLength = 8;
    this.tbxData1bin1.Name = "tbxData1bin1";
    this.tbxData1bin1.Size = new Size(89, 22);
    this.tbxData1bin1.TabIndex = 11;
    this.tbxData1bin1.Text = "10001010";
    this.tbxChecksumHex.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxChecksumHex.Location = new Point(143, 219);
    this.tbxChecksumHex.Margin = new Padding(4);
    this.tbxChecksumHex.MaxLength = 2;
    this.tbxChecksumHex.Name = "tbxChecksumHex";
    this.tbxChecksumHex.Size = new Size(43, 22);
    this.tbxChecksumHex.TabIndex = 10;
    this.tbxChecksumHex.Text = "1F";
    this.tbxChecksumHex.TextAlign = HorizontalAlignment.Center;
    this.Label5.AutoSize = true;
    this.Label5.Location = new Point(28, 221);
    this.Label5.Margin = new Padding(4, 0, 4, 0);
    this.Label5.Name = "Label5";
    this.Label5.Size = new Size(73, 16 /*0x10*/);
    this.Label5.TabIndex = 9;
    this.Label5.Text = "Checksum:";
    this.Button1.Location = new Point(30, 157);
    this.Button1.Margin = new Padding(4);
    this.Button1.Name = "Button1";
    this.Button1.Size = new Size(268, 41);
    this.Button1.TabIndex = 8;
    this.Button1.Text = "Re-Calc Checksum (last byte)";
    this.Button1.UseVisualStyleBackColor = true;
    this.tbxData3hex.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData3hex.Location = new Point(118, 117);
    this.tbxData3hex.Margin = new Padding(4);
    this.tbxData3hex.MaxLength = 5;
    this.tbxData3hex.Name = "tbxData3hex";
    this.tbxData3hex.Size = new Size(68, 22);
    this.tbxData3hex.TabIndex = 7;
    this.tbxData3hex.Text = "3F1F";
    this.Label4.AutoSize = true;
    this.Label4.Location = new Point(27, 119);
    this.Label4.Margin = new Padding(4, 0, 4, 0);
    this.Label4.Name = "Label4";
    this.Label4.Size = new Size(39, 16 /*0x10*/);
    this.Label4.TabIndex = 6;
    this.Label4.Text = "Data:";
    this.tbxData2hex.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData2hex.Location = new Point(118, 85);
    this.tbxData2hex.Margin = new Padding(4);
    this.tbxData2hex.MaxLength = 5;
    this.tbxData2hex.Name = "tbxData2hex";
    this.tbxData2hex.Size = new Size(68, 22);
    this.tbxData2hex.TabIndex = 5;
    this.tbxData2hex.Text = "40F0";
    this.Label3.AutoSize = true;
    this.Label3.Location = new Point(27, 87);
    this.Label3.Margin = new Padding(4, 0, 4, 0);
    this.Label3.Name = "Label3";
    this.Label3.Size = new Size(39, 16 /*0x10*/);
    this.Label3.TabIndex = 4;
    this.Label3.Text = "Data:";
    this.tbxData1hex.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxData1hex.Location = new Point(118, 53);
    this.tbxData1hex.Margin = new Padding(4);
    this.tbxData1hex.MaxLength = 5;
    this.tbxData1hex.Name = "tbxData1hex";
    this.tbxData1hex.Size = new Size(68, 22);
    this.tbxData1hex.TabIndex = 3;
    this.tbxData1hex.Text = "8AFC";
    this.Label2.AutoSize = true;
    this.Label2.Location = new Point(27, 55);
    this.Label2.Margin = new Padding(4, 0, 4, 0);
    this.Label2.Name = "Label2";
    this.Label2.Size = new Size(39, 16 /*0x10*/);
    this.Label2.TabIndex = 2;
    this.Label2.Text = "Data:";
    this.tbxModIDhex.Font = new Font("Courier New", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.tbxModIDhex.Location = new Point(118, 23);
    this.tbxModIDhex.Margin = new Padding(4);
    this.tbxModIDhex.MaxLength = 10;
    this.tbxModIDhex.Name = "tbxModIDhex";
    this.tbxModIDhex.Size = new Size(102, 22);
    this.tbxModIDhex.TabIndex = 1;
    this.tbxModIDhex.Text = "720-01-02";
    this.Label1.AutoSize = true;
    this.Label1.Location = new Point(27, 25);
    this.Label1.Margin = new Padding(4, 0, 4, 0);
    this.Label1.Name = "Label1";
    this.Label1.Size = new Size(71, 16 /*0x10*/);
    this.Label1.TabIndex = 0;
    this.Label1.Text = "Module ID:";
    this.TabPage3.BackColor = SystemColors.Control;
    this.TabPage3.Controls.Add((Control) this.TextBox6);
    this.TabPage3.Controls.Add((Control) this.TextBox2);
    this.TabPage3.Controls.Add((Control) this.Label12);
    this.TabPage3.Controls.Add((Control) this.Label9);
    this.TabPage3.Controls.Add((Control) this.chkDeduceDownloadAB);
    this.TabPage3.Controls.Add((Control) this.btnDeduceSaveInfo);
    this.TabPage3.Controls.Add((Control) this.wbDeducer);
    this.TabPage3.Controls.Add((Control) this.btnDeduceOpenETIS);
    this.TabPage3.Location = new Point(4, 25);
    this.TabPage3.Name = "TabPage3";
    this.TabPage3.Size = new Size(991, 562);
    this.TabPage3.TabIndex = 2;
    this.TabPage3.Text = "Deducer - Get Data";
    this.TextBox2.Anchor = AnchorStyles.Top | AnchorStyles.Right;
    this.TextBox2.BackColor = SystemColors.Info;
    this.TextBox2.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.TextBox2.Location = new Point(596, 232);
    this.TextBox2.Multiline = true;
    this.TextBox2.Name = "TextBox2";
    this.TextBox2.Size = new Size(199, 308);
    this.TextBox2.TabIndex = 9;
    this.TextBox2.Text = componentResourceManager.GetString("TextBox2.Text");
    this.Label12.AutoSize = true;
    this.Label12.Location = new Point(214, 48 /*0x30*/);
    this.Label12.Name = "Label12";
    this.Label12.Size = new Size(456, 16 /*0x10*/);
    this.Label12.TabIndex = 2;
    this.Label12.Text = "When prompted, save the .AB file in the \"Deducer\" subfolder of this program.";
    this.Label9.AutoSize = true;
    this.Label9.Location = new Point(18, 48 /*0x30*/);
    this.Label9.Name = "Label9";
    this.Label9.Size = new Size(138, 16 /*0x10*/);
    this.Label9.TabIndex = 8;
    this.Label9.Text = "Search the VIN below:";
    this.chkDeduceDownloadAB.AutoSize = true;
    this.chkDeduceDownloadAB.Checked = true;
    this.chkDeduceDownloadAB.CheckState = CheckState.Checked;
    this.chkDeduceDownloadAB.Enabled = false;
    this.chkDeduceDownloadAB.Location = new Point(340, 21);
    this.chkDeduceDownloadAB.Name = "chkDeduceDownloadAB";
    this.chkDeduceDownloadAB.Size = new Size(111, 20);
    this.chkDeduceDownloadAB.TabIndex = 7;
    this.chkDeduceDownloadAB.Text = "Download .AB";
    this.chkDeduceDownloadAB.UseVisualStyleBackColor = true;
    this.chkDeduceDownloadAB.Visible = false;
    this.btnDeduceSaveInfo.Location = new Point(208 /*0xD0*/, 17);
    this.btnDeduceSaveInfo.Name = "btnDeduceSaveInfo";
    this.btnDeduceSaveInfo.Size = new Size(96 /*0x60*/, 26);
    this.btnDeduceSaveInfo.TabIndex = 5;
    this.btnDeduceSaveInfo.Text = "Save Info";
    this.btnDeduceSaveInfo.UseVisualStyleBackColor = true;
    this.wbDeducer.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
    this.wbDeducer.Location = new Point(15, 86);
    this.wbDeducer.MinimumSize = new Size(20, 20);
    this.wbDeducer.Name = "wbDeducer";
    this.wbDeducer.Size = new Size(552, 454);
    this.wbDeducer.TabIndex = 4;
    this.btnDeduceOpenETIS.Location = new Point(15, 17);
    this.btnDeduceOpenETIS.Name = "btnDeduceOpenETIS";
    this.btnDeduceOpenETIS.Size = new Size(106, 26);
    this.btnDeduceOpenETIS.TabIndex = 2;
    this.btnDeduceOpenETIS.Text = "Open ETIS";
    this.btnDeduceOpenETIS.UseVisualStyleBackColor = true;
    this.TabPage4.BackColor = SystemColors.Control;
    this.TabPage4.Controls.Add((Control) this.chkDeduceDoCCC);
    this.TabPage4.Controls.Add((Control) this.Button8);
    this.TabPage4.Controls.Add((Control) this.Label14);
    this.TabPage4.Controls.Add((Control) this.TextBox1);
    this.TabPage4.Controls.Add((Control) this.Label13);
    this.TabPage4.Controls.Add((Control) this.Label11);
    this.TabPage4.Controls.Add((Control) this.Label10);
    this.TabPage4.Controls.Add((Control) this.lstDeduceYears);
    this.TabPage4.Controls.Add((Control) this.lstDeduceModels);
    this.TabPage4.Controls.Add((Control) this.tbxDeduceReport);
    this.TabPage4.Controls.Add((Control) this.btnDeduceFigureIt);
    this.TabPage4.Controls.Add((Control) this.btnDeduceLoadOptions);
    this.TabPage4.Controls.Add((Control) this.lstDeduceFactoryOptions);
    this.TabPage4.Location = new Point(4, 25);
    this.TabPage4.Name = "TabPage4";
    this.TabPage4.Size = new Size(991, 562);
    this.TabPage4.TabIndex = 3;
    this.TabPage4.Text = "Deducer - Feature by Vehicles";
    this.chkDeduceDoCCC.AutoSize = true;
    this.chkDeduceDoCCC.Location = new Point(622, 20);
    this.chkDeduceDoCCC.Name = "chkDeduceDoCCC";
    this.chkDeduceDoCCC.Size = new Size(180, 20);
    this.chkDeduceDoCCC.TabIndex = 12;
    this.chkDeduceDoCCC.Text = "Compare CCC bits as well";
    this.chkDeduceDoCCC.UseVisualStyleBackColor = true;
    this.Button8.Location = new Point(622, 425);
    this.Button8.Name = "Button8";
    this.Button8.Size = new Size(173, 27);
    this.Button8.TabIndex = 11;
    this.Button8.Text = "Try Every Option";
    this.Button8.UseVisualStyleBackColor = true;
    this.Button8.Visible = false;
    this.Label14.AutoSize = true;
    this.Label14.Location = new Point(12, 428);
    this.Label14.Name = "Label14";
    this.Label14.Size = new Size(522, 16 /*0x10*/);
    this.Label14.TabIndex = 10;
    this.Label14.Text = "\"Perfect Bits\" are listed at the bottom.  Bits are numbered from left to right starting at zero.";
    this.TextBox1.BackColor = SystemColors.Info;
    this.TextBox1.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.TextBox1.Location = new Point(622, 81);
    this.TextBox1.Multiline = true;
    this.TextBox1.Name = "TextBox1";
    this.TextBox1.Size = new Size(173, 335);
    this.TextBox1.TabIndex = 9;
    this.TextBox1.Text = componentResourceManager.GetString("TextBox1.Text");
    this.Label13.AutoSize = true;
    this.Label13.Location = new Point(12, 212);
    this.Label13.Name = "Label13";
    this.Label13.Size = new Size(133, 16 /*0x10*/);
    this.Label13.TabIndex = 8;
    this.Label13.Text = "Review results below";
    this.Label11.AutoSize = true;
    this.Label11.Location = new Point(12, 140);
    this.Label11.Name = "Label11";
    this.Label11.Size = new Size(161, 16 /*0x10*/);
    this.Label11.TabIndex = 7;
    this.Label11.Text = "Select Years and Models:";
    this.Label10.AutoSize = true;
    this.Label10.Location = new Point(12, 69);
    this.Label10.Name = "Label10";
    this.Label10.Size = new Size(155, 16 /*0x10*/);
    this.Label10.TabIndex = 6;
    this.Label10.Text = "Select feature to deduce:";
    this.lstDeduceYears.FormattingEnabled = true;
    this.lstDeduceYears.IntegralHeight = false;
    this.lstDeduceYears.Location = new Point(218, 126);
    this.lstDeduceYears.Name = "lstDeduceYears";
    this.lstDeduceYears.Size = new Size(120, 72);
    this.lstDeduceYears.TabIndex = 5;
    this.lstDeduceModels.FormattingEnabled = true;
    this.lstDeduceModels.IntegralHeight = false;
    this.lstDeduceModels.Location = new Point(353, 126);
    this.lstDeduceModels.Name = "lstDeduceModels";
    this.lstDeduceModels.Size = new Size(233, 72);
    this.lstDeduceModels.TabIndex = 4;
    this.tbxDeduceReport.BorderStyle = BorderStyle.FixedSingle;
    this.tbxDeduceReport.Location = new Point(15, 235);
    this.tbxDeduceReport.Multiline = true;
    this.tbxDeduceReport.Name = "tbxDeduceReport";
    this.tbxDeduceReport.ScrollBars = ScrollBars.Vertical;
    this.tbxDeduceReport.Size = new Size(588, 181);
    this.tbxDeduceReport.TabIndex = 3;
    this.btnDeduceFigureIt.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.btnDeduceFigureIt.Location = new Point(622, 47);
    this.btnDeduceFigureIt.Name = "btnDeduceFigureIt";
    this.btnDeduceFigureIt.Size = new Size(173, 28);
    this.btnDeduceFigureIt.TabIndex = 2;
    this.btnDeduceFigureIt.Text = "Find Perfect Bits";
    this.btnDeduceFigureIt.UseVisualStyleBackColor = true;
    this.btnDeduceLoadOptions.Location = new Point(15, 20);
    this.btnDeduceLoadOptions.Name = "btnDeduceLoadOptions";
    this.btnDeduceLoadOptions.Size = new Size(155, 28);
    this.btnDeduceLoadOptions.TabIndex = 1;
    this.btnDeduceLoadOptions.Text = "Load Stored Data";
    this.btnDeduceLoadOptions.UseVisualStyleBackColor = true;
    this.lstDeduceFactoryOptions.FormattingEnabled = true;
    this.lstDeduceFactoryOptions.ItemHeight = 16 /*0x10*/;
    this.lstDeduceFactoryOptions.Location = new Point(218, 20);
    this.lstDeduceFactoryOptions.Name = "lstDeduceFactoryOptions";
    this.lstDeduceFactoryOptions.SelectionMode = SelectionMode.MultiExtended;
    this.lstDeduceFactoryOptions.Size = new Size(368, 84);
    this.lstDeduceFactoryOptions.TabIndex = 0;
    this.TabPage5.BackColor = SystemColors.Control;
    this.TabPage5.Controls.Add((Control) this.Button10);
    this.TabPage5.Controls.Add((Control) this.TextBox4);
    this.TabPage5.Controls.Add((Control) this.Label21);
    this.TabPage5.Controls.Add((Control) this.lstBit_Modules);
    this.TabPage5.Controls.Add((Control) this.Button6);
    this.TabPage5.Controls.Add((Control) this.Button5);
    this.TabPage5.Controls.Add((Control) this.Label20);
    this.TabPage5.Controls.Add((Control) this.Label19);
    this.TabPage5.Controls.Add((Control) this.lstBit_Years);
    this.TabPage5.Controls.Add((Control) this.lstBit_Models);
    this.TabPage5.Controls.Add((Control) this.Label17);
    this.TabPage5.Controls.Add((Control) this.TextBox3);
    this.TabPage5.Controls.Add((Control) this.Label18);
    this.TabPage5.Controls.Add((Control) this.tbxDeduceReport2);
    this.TabPage5.Controls.Add((Control) this.Button4);
    this.TabPage5.Location = new Point(4, 25);
    this.TabPage5.Name = "TabPage5";
    this.TabPage5.Padding = new Padding(3);
    this.TabPage5.Size = new Size(991, 562);
    this.TabPage5.TabIndex = 4;
    this.TabPage5.Text = "Deducer - Vehicle/Feature by Bit";
    this.Button10.Location = new Point(630, 422);
    this.Button10.Name = "Button10";
    this.Button10.Size = new Size(173, 28);
    this.Button10.TabIndex = 31 /*0x1F*/;
    this.Button10.Text = "Analyze All bits";
    this.Button10.UseVisualStyleBackColor = true;
    this.TextBox4.Location = new Point(226, 253);
    this.TextBox4.Name = "TextBox4";
    this.TextBox4.Size = new Size(76, 22);
    this.TextBox4.TabIndex = 30;
    this.TextBox4.Text = "0";
    this.TextBox4.TextAlign = HorizontalAlignment.Center;
    this.Label21.AutoSize = true;
    this.Label21.Location = new Point(20, 256 /*0x0100*/);
    this.Label21.Name = "Label21";
    this.Label21.Size = new Size(150, 16 /*0x10*/);
    this.Label21.TabIndex = 29;
    this.Label21.Text = "Select Bit Index (0 to 39):";
    this.lstBit_Modules.FormattingEnabled = true;
    this.lstBit_Modules.ItemHeight = 16 /*0x10*/;
    this.lstBit_Modules.Location = new Point(226, 152);
    this.lstBit_Modules.Name = "lstBit_Modules";
    this.lstBit_Modules.Size = new Size(365, 84);
    this.lstBit_Modules.TabIndex = 28;
    this.Button6.Location = new Point(23, 152);
    this.Button6.Name = "Button6";
    this.Button6.Size = new Size(155, 28);
    this.Button6.TabIndex = 27;
    this.Button6.Text = "Load Modules";
    this.Button6.UseVisualStyleBackColor = true;
    this.Button5.Location = new Point(23, 23);
    this.Button5.Name = "Button5";
    this.Button5.Size = new Size(155, 28);
    this.Button5.TabIndex = 26;
    this.Button5.Text = "Load Stored Data";
    this.Button5.UseVisualStyleBackColor = true;
    this.Label20.AutoSize = true;
    this.Label20.Location = new Point(20, 199);
    this.Label20.Name = "Label20";
    this.Label20.Size = new Size(96 /*0x60*/, 16 /*0x10*/);
    this.Label20.TabIndex = 25;
    this.Label20.Text = "Select Module:";
    this.Label19.AutoSize = true;
    this.Label19.Location = new Point(20, 72);
    this.Label19.Name = "Label19";
    this.Label19.Size = new Size(161, 16 /*0x10*/);
    this.Label19.TabIndex = 24;
    this.Label19.Text = "Select Years and Models:";
    this.lstBit_Years.FormattingEnabled = true;
    this.lstBit_Years.IntegralHeight = false;
    this.lstBit_Years.Location = new Point(226, 23);
    this.lstBit_Years.Name = "lstBit_Years";
    this.lstBit_Years.Size = new Size(120, 101);
    this.lstBit_Years.TabIndex = 23;
    this.lstBit_Models.FormattingEnabled = true;
    this.lstBit_Models.IntegralHeight = false;
    this.lstBit_Models.Location = new Point(358, 23);
    this.lstBit_Models.Name = "lstBit_Models";
    this.lstBit_Models.Size = new Size(233, 101);
    this.lstBit_Models.TabIndex = 22;
    this.Label17.AutoSize = true;
    this.Label17.Location = new Point(20, 495);
    this.Label17.Name = "Label17";
    this.Label17.Size = new Size(522, 16 /*0x10*/);
    this.Label17.TabIndex = 21;
    this.Label17.Text = "\"Perfect Bits\" are listed at the bottom.  Bits are numbered from left to right starting at zero.";
    this.TextBox3.BackColor = SystemColors.Info;
    this.TextBox3.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.TextBox3.Location = new Point(630, 72);
    this.TextBox3.Multiline = true;
    this.TextBox3.Name = "TextBox3";
    this.TextBox3.Size = new Size(173, 344);
    this.TextBox3.TabIndex = 20;
    this.TextBox3.Text = "This tool attempts to deduce which feature(s) corresponds to the chosen module bit.  \r\n\r\nThis is a statistical analysis and only identifies consistencies -- not guarantees.";
    this.Label18.AutoSize = true;
    this.Label18.Location = new Point(20, 320);
    this.Label18.Name = "Label18";
    this.Label18.Size = new Size(133, 16 /*0x10*/);
    this.Label18.TabIndex = 19;
    this.Label18.Text = "Review results below";
    this.tbxDeduceReport2.BorderStyle = BorderStyle.FixedSingle;
    this.tbxDeduceReport2.Location = new Point(24, 343);
    this.tbxDeduceReport2.MaxLength = 5000000;
    this.tbxDeduceReport2.Multiline = true;
    this.tbxDeduceReport2.Name = "tbxDeduceReport2";
    this.tbxDeduceReport2.ScrollBars = ScrollBars.Vertical;
    this.tbxDeduceReport2.Size = new Size(588, 119);
    this.tbxDeduceReport2.TabIndex = 14;
    this.Button4.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.Button4.Location = new Point(630, 23);
    this.Button4.Name = "Button4";
    this.Button4.Size = new Size(173, 28);
    this.Button4.TabIndex = 13;
    this.Button4.Text = "Find Feature";
    this.Button4.UseVisualStyleBackColor = true;
    this.TabPage6.BackColor = SystemColors.Control;
    this.TabPage6.Controls.Add((Control) this.btnBrowseRefresh);
    this.TabPage6.Controls.Add((Control) this.lvwBrowser);
    this.TabPage6.Location = new Point(4, 25);
    this.TabPage6.Name = "TabPage6";
    this.TabPage6.Padding = new Padding(3);
    this.TabPage6.Size = new Size(991, 562);
    this.TabPage6.TabIndex = 5;
    this.TabPage6.Text = "AsBuilt Browser";
    this.btnBrowseRefresh.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
    this.btnBrowseRefresh.Location = new Point(6, 13);
    this.btnBrowseRefresh.Name = "btnBrowseRefresh";
    this.btnBrowseRefresh.Size = new Size(103, 32 /*0x20*/);
    this.btnBrowseRefresh.TabIndex = 1;
    this.btnBrowseRefresh.Text = "Refresh";
    this.btnBrowseRefresh.UseVisualStyleBackColor = true;
    this.lvwBrowser.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
    this.lvwBrowser.Columns.AddRange(new ColumnHeader[5]
    {
      this.ColumnHeader10,
      this.ColumnHeader11,
      this.ColumnHeader12,
      this.ColumnHeader13,
      this.ColumnHeader14
    });
    this.lvwBrowser.ContextMenuStrip = this.ContextMenuStrip2;
    this.lvwBrowser.FullRowSelect = true;
    this.lvwBrowser.GridLines = true;
    this.lvwBrowser.HideSelection = false;
    this.lvwBrowser.Location = new Point(6, 54);
    this.lvwBrowser.Name = "lvwBrowser";
    this.lvwBrowser.Size = new Size(979, 495);
    this.lvwBrowser.TabIndex = 0;
    this.lvwBrowser.UseCompatibleStateImageBehavior = false;
    this.lvwBrowser.View = View.Details;
    this.ColumnHeader10.Text = "Name";
    this.ColumnHeader10.Width = 250;
    this.ColumnHeader11.Text = "Date";
    this.ColumnHeader11.Width = 150;
    this.ColumnHeader12.Text = "Year";
    this.ColumnHeader12.Width = 70;
    this.ColumnHeader13.Text = "Model";
    this.ColumnHeader13.Width = 220;
    this.ColumnHeader14.Text = "VIN";
    this.ColumnHeader14.Width = 225;
    this.ContextMenuStrip2.ImageScalingSize = new Size(20, 20);
    this.ContextMenuStrip2.Items.AddRange(new ToolStripItem[6]
    {
      (ToolStripItem) this.SetAsCompare1ToolStripMenuItem,
      (ToolStripItem) this.SetAsCompare2ToolStripMenuItem,
      (ToolStripItem) this.SetAsCompare3ToolStripMenuItem,
      (ToolStripItem) this.SetAsCompare4ToolStripMenuItem,
      (ToolStripItem) this.ToolStripMenuItem1,
      (ToolStripItem) this.DeleteFileToolStripMenuItem
    });
    this.ContextMenuStrip2.Name = "ContextMenuStrip2";
    this.ContextMenuStrip2.Size = new Size(176 /*0xB0*/, 120);
    this.SetAsCompare1ToolStripMenuItem.Name = "SetAsCompare1ToolStripMenuItem";
    this.SetAsCompare1ToolStripMenuItem.Size = new Size(175, 22);
    this.SetAsCompare1ToolStripMenuItem.Text = "Set as Compare # 1";
    this.SetAsCompare2ToolStripMenuItem.Name = "SetAsCompare2ToolStripMenuItem";
    this.SetAsCompare2ToolStripMenuItem.Size = new Size(175, 22);
    this.SetAsCompare2ToolStripMenuItem.Text = "Set as Compare # 2";
    this.SetAsCompare3ToolStripMenuItem.Name = "SetAsCompare3ToolStripMenuItem";
    this.SetAsCompare3ToolStripMenuItem.Size = new Size(175, 22);
    this.SetAsCompare3ToolStripMenuItem.Text = "Set as Compare # 3";
    this.SetAsCompare4ToolStripMenuItem.Name = "SetAsCompare4ToolStripMenuItem";
    this.SetAsCompare4ToolStripMenuItem.Size = new Size(175, 22);
    this.SetAsCompare4ToolStripMenuItem.Text = "Set as Compare # 4";
    this.ToolStripMenuItem1.Name = "ToolStripMenuItem1";
    this.ToolStripMenuItem1.Size = new Size(172, 6);
    this.DeleteFileToolStripMenuItem.Name = "DeleteFileToolStripMenuItem";
    this.DeleteFileToolStripMenuItem.Size = new Size(175, 22);
    this.DeleteFileToolStripMenuItem.Text = "Delete File";
    this.Label8.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
    this.Label8.AutoSize = true;
    this.Label8.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.Label8.ForeColor = Color.FromArgb(0, 0, 192 /*0xC0*/);
    this.Label8.Location = new Point(269, 622);
    this.Label8.Name = "Label8";
    this.Label8.Size = new Size(347, 15);
    this.Label8.TabIndex = 1;
    this.Label8.Text = "Written by Jesse Yeager                    www.CompulsiveCode.com";
    this.PictureBox1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
    this.PictureBox1.Cursor = Cursors.Hand;
    this.PictureBox1.Image = (Image) componentResourceManager.GetObject("PictureBox1.Image");
    this.PictureBox1.Location = new Point(11, 601);
    this.PictureBox1.Name = "PictureBox1";
    this.PictureBox1.Size = new Size(115, 52);
    this.PictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
    this.PictureBox1.TabIndex = 3;
    this.PictureBox1.TabStop = false;
    this.chkShowOnlyMismatches.AutoSize = true;
    this.chkShowOnlyMismatches.Location = new Point(167, 206);
    this.chkShowOnlyMismatches.Name = "chkShowOnlyMismatches";
    this.chkShowOnlyMismatches.Size = new Size(222, 20);
    this.chkShowOnlyMismatches.TabIndex = 20;
    this.chkShowOnlyMismatches.Text = "Only Show Non-Matching Groups";
    this.chkShowOnlyMismatches.UseVisualStyleBackColor = true;
    this.TextBox6.Anchor = AnchorStyles.Top | AnchorStyles.Right;
    this.TextBox6.BackColor = SystemColors.Info;
    this.TextBox6.Font = new Font("Microsoft Sans Serif", 9f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.TextBox6.ForeColor = Color.Red;
    this.TextBox6.Location = new Point(596, 86);
    this.TextBox6.Multiline = true;
    this.TextBox6.Name = "TextBox6";
    this.TextBox6.Size = new Size(199, 124);
    this.TextBox6.TabIndex = 10;
    this.TextBox6.Text = "The Deducer tool is now unusable, due to the ETIS site being shut down.  Unless there is another site to correlate VIN to vehicle features, this will remain broken.";
    this.AutoScaleMode = AutoScaleMode.None;
    this.ClientSize = new Size(1029, 646);
    this.Controls.Add((Control) this.Label8);
    this.Controls.Add((Control) this.TabControl1);
    this.Controls.Add((Control) this.PictureBox1);
    this.Font = new Font("Microsoft Sans Serif", 9.75f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
    this.Icon = (Icon) componentResourceManager.GetObject("$this.Icon");
    this.Margin = new Padding(4);
    this.MinimumSize = new Size(913, 500);
    this.Name = nameof (Form1);
    this.Text = "As-Built Compare";
    this.TabControl1.ResumeLayout(false);
    this.TabPage1.ResumeLayout(false);
    this.TabPage1.PerformLayout();
    this.ContextMenuStrip1.ResumeLayout(false);
    this.TabPage2.ResumeLayout(false);
    this.TabPage2.PerformLayout();
    this.TabPage3.ResumeLayout(false);
    this.TabPage3.PerformLayout();
    this.TabPage4.ResumeLayout(false);
    this.TabPage4.PerformLayout();
    this.TabPage5.ResumeLayout(false);
    this.TabPage5.PerformLayout();
    this.TabPage6.ResumeLayout(false);
    this.ContextMenuStrip2.ResumeLayout(false);
    ((ISupportInitialize) this.PictureBox1).EndInit();
    this.ResumeLayout(false);
    this.PerformLayout();
            this.TabPage1.Click += new System.EventHandler(this.TabPage1_Click);
            this.TabPage2.Click += new System.EventHandler(this.TabPage2_Click);
            this.tbxData2hex.TextChanged += new System.EventHandler(this.TextBox3_TextChanged);
            this.Label3.Click += new System.EventHandler(this.Label3_Click);
            this.tbxData1hex.TextChanged += new System.EventHandler(this.tbxData1hex_TextChanged);
            this.tbxChecksumHex.TextChanged += new System.EventHandler(this.tbxChecksumHex_TextChanged);
            this.Button1.Click += new System.EventHandler(this.Button1_Click);
            this.tbxData3hex.TextChanged += new System.EventHandler(this.tbxData3hex_TextChanged);
            this.btnCompBrowse2.Click += new System.EventHandler(this.btnCompBrowse2_Click);
            this.btnCompBrowse1.Click += new System.EventHandler(this.btnCompBrowse1_Click);
            this.ListView1.SelectedIndexChanged += new System.EventHandler(this.ListView1_SelectedIndexChanged);
            this.btnCompLoad.Click += new System.EventHandler(this.Button2_Click);
            this.ContextMenuStrip1.Opening += new System.CancelEventHandler(this.ContextMenuStrip1_Opening);
            this.CopyToolStripMenuItem.Click += new System.EventHandler(this.CopyToolStripMenuItem_Click);
            this.EntireLineToolStripMenuItem.Click += new System.EventHandler(this.EntireLineToolStripMenuItem_Click);
            this.Data1hexToolStripMenuItem.Click += new System.EventHandler(this.Data1hexToolStripMenuItem_Click);
            this.Data2hexToolStripMenuItem.Click += new System.EventHandler(this.Data2hexToolStripMenuItem_Click);
            this.Data3hexToolStripMenuItem.Click += new System.EventHandler(this.Data3hexToolStripMenuItem_Click);
            this.BinaryToolStripMenuItem.Click += new System.EventHandler(this.BinaryToolStripMenuItem_Click);
            this.btnDeduceOpenETIS.Click += new System.EventHandler(this.Button2_Click_1);
            this.wbDeducer.DocumentCompleted += new System.WebBrowserDocumentCompletedEventHandler(this.wbDeducer_DocumentCompleted);
            this.wbDeducer.Navigating += new System.WebBrowserNavigatingEventHandler(this.wbDeducer_Navigating);
            this.wbDeducer.FileDownload += new System.EventHandler(this.wbDeducer_FileDownload);
            this.btnDeduceSaveInfo.Click += new System.EventHandler(this.Button3_Click);
            this.TabPage4.Click += new System.EventHandler(this.TabPage4_Click);
            this.btnDeduceFigureIt.Click += new System.EventHandler(this.btnDeduceFigureIt_Click);
            this.btnDeduceLoadOptions.Click += new System.EventHandler(this.btnDeduceLoadOptions_Click);
            this.Button3.Click += new System.EventHandler(this.Button3_Click_1);
            this.Button2.Click += new System.EventHandler(this.Button2_Click_2);
            this.TabPage5.Click += new System.EventHandler(this.TabPage5_Click);
            this.Button4.Click += new System.EventHandler(this.Button4_Click);
            this.Button8.Click += new System.EventHandler(this.Button8_Click);
            this.Button6.Click += new System.EventHandler(this.Button6_Click_1);
            this.Button5.Click += new System.EventHandler(this.Button5_Click_1);
            this.Button9.Click += new System.EventHandler(this.Button9_Click);
            this.Button7.Click += new System.EventHandler(this.Button7_Click);
            this.lvwBrowser.SelectedIndexChanged += new System.EventHandler(this.lvwBrowser_SelectedIndexChanged);
            this.lvwBrowser.ColumnClick += new System.ColumnClickEventHandler(this.lvwBrowser_ColumnClick);
            this.btnBrowseRefresh.Click += new System.EventHandler(this.Button10_Click);
            this.ContextMenuStrip2.Opening += new System.CancelEventHandler(this.ContextMenuStrip2_Opening);
            this.SetAsCompare1ToolStripMenuItem.Click += new System.EventHandler(this.SetAsCompare1ToolStripMenuItem_Click);
            this.SetAsCompare2ToolStripMenuItem.Click += new System.EventHandler(this.SetAsCompare2ToolStripMenuItem_Click);
            this.SetAsCompare3ToolStripMenuItem.Click += new System.EventHandler(this.SetAsCompare3ToolStripMenuItem_Click);
            this.SetAsCompare4ToolStripMenuItem.Click += new System.EventHandler(this.SetAsCompare4ToolStripMenuItem_Click);
            this.DeleteFileToolStripMenuItem.Click += new System.EventHandler(this.DeleteFileToolStripMenuItem_Click);
            this.PictureBox1.Click += new System.EventHandler(this.PictureBox1_Click);
            this.ExportModuleToolStripMenuItem.Click += new System.EventHandler(this.ExportModuleToolStripMenuItem_Click);
            this.ExportModuleToolStripMenuItem.DropDownOpening += new System.EventHandler(this.ExportModuleToolStripMenuItem_DropDownOpening);
            this.ToUCDSToolStripMenuItem.Click += new System.EventHandler(this.ToUCDSToolStripMenuItem_Click);
            this.ToABTToolStripMenuItem.Click += new System.EventHandler(this.ToABTToolStripMenuItem_Click);
            this.Button10.Click += new System.EventHandler(this.Button10_Click_1);
            this.chkShowOnlyMismatches.CheckedChanged += new System.EventHandler(this.CheckBox1_CheckedChanged);
        }

        #endregion

    private TabPage TabPage1;
    private TabPage TabPage2;
    private TextBox tbxData2hex;
    private Label Label3;
    private TextBox tbxData1hex;
    private TextBox tbxChecksumHex;
    private Button Button1;
    private TextBox tbxData3hex;
    private Button btnCompBrowse2;
    private Button btnCompBrowse1;
    private ListView ListView1;
    private Button btnCompLoad;
    private ContextMenuStrip ContextMenuStrip1;
    private ToolStripMenuItem CopyToolStripMenuItem;
    private ToolStripMenuItem EntireLineToolStripMenuItem;
    private ToolStripMenuItem Data1hexToolStripMenuItem;
    private ToolStripMenuItem Data2hexToolStripMenuItem;
    private ToolStripMenuItem Data3hexToolStripMenuItem;
    private ToolStripMenuItem BinaryToolStripMenuItem;
    private Button btnDeduceOpenETIS;
    private WebBrowser wbDeducer;
    private Button btnDeduceSaveInfo;
    private TabPage TabPage4;
    private Button btnDeduceFigureIt;
    private Button btnDeduceLoadOptions;
    private Button Button3;
    private Button Button2;
    private TabPage TabPage5;
    private Button Button4;
    private Button Button8;
    private Button Button6;
    private Button Button5;
    private Button Button9;
    private Button Button7;
    private ListView lvwBrowser;
    private Button btnBrowseRefresh;
    private ContextMenuStrip ContextMenuStrip2;
    private ToolStripMenuItem SetAsCompare1ToolStripMenuItem;
    private ToolStripMenuItem SetAsCompare2ToolStripMenuItem;
    private ToolStripMenuItem SetAsCompare3ToolStripMenuItem;
    private ToolStripMenuItem SetAsCompare4ToolStripMenuItem;
    private ToolStripMenuItem DeleteFileToolStripMenuItem;
    private PictureBox PictureBox1;
    private ToolStripMenuItem ExportModuleToolStripMenuItem;
    private ToolStripMenuItem ToUCDSToolStripMenuItem;
    private ToolStripMenuItem ToABTToolStripMenuItem;
    private Button Button10;
    private CheckBox chkShowOnlyMismatches;
    }
}
