//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsBuiltExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsBuiltExplorer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits &amp; Thanks.
        /// </summary>
        public static string About_Credits {
            get {
                return ResourceManager.GetString("About_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        public static string About_Developer {
            get {
                return ResourceManager.GetString("About_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on GitHub.
        /// </summary>
        public static string About_GitHub {
            get {
                return ResourceManager.GetString("About_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsBuilt Explorer.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze All bits.
        /// </summary>
        public static string Bit_AnalyzeAll {
            get {
                return ResourceManager.GetString("Bit_AnalyzeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Feature.
        /// </summary>
        public static string Bit_FindFeature {
            get {
                return ResourceManager.GetString("Bit_FindFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Modules.
        /// </summary>
        public static string Bit_LoadModules {
            get {
                return ResourceManager.GetString("Bit_LoadModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Stored Data.
        /// </summary>
        public static string Bit_LoadStored {
            get {
                return ResourceManager.GetString("Bit_LoadStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool attempts to deduce which feature(s) corresponds to the chosen module bit.
        ///
        ///This is a statistical analysis and only identifies consistencies -- not guarantees..
        /// </summary>
        public static string Bit_Note_Desc {
            get {
                return ResourceManager.GetString("Bit_Note_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bit Index (0 to 39):.
        /// </summary>
        public static string Bit_SelectBit {
            get {
                return ResourceManager.GetString("Bit_SelectBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Module:.
        /// </summary>
        public static string Bit_SelectModule {
            get {
                return ResourceManager.GetString("Bit_SelectModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Btn_Browse {
            get {
                return ResourceManager.GetString("Btn_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string Btn_Calculate {
            get {
                return ResourceManager.GetString("Btn_Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string Btn_Checking {
            get {
                return ResourceManager.GetString("Btn_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Now.
        /// </summary>
        public static string Btn_CheckNow {
            get {
                return ResourceManager.GetString("Btn_CheckNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Database.
        /// </summary>
        public static string Btn_ClearDatabase {
            get {
                return ResourceManager.GetString("Btn_ClearDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string Btn_Convert {
            get {
                return ResourceManager.GetString("Btn_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode.
        /// </summary>
        public static string Btn_Decode {
            get {
                return ResourceManager.GetString("Btn_Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Now.
        /// </summary>
        public static string Btn_DownloadNow {
            get {
                return ResourceManager.GetString("Btn_DownloadNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Btn_Go {
            get {
                return ResourceManager.GetString("Btn_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Files.
        /// </summary>
        public static string Btn_Load {
            get {
                return ResourceManager.GetString("Btn_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string Btn_OpenExternal {
            get {
                return ResourceManager.GetString("Btn_OpenExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string Btn_RemindLater {
            get {
                return ResourceManager.GetString("Btn_RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        public static string Btn_Scan {
            get {
                return ResourceManager.GetString("Btn_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip This Version.
        /// </summary>
        public static string Btn_Skip {
            get {
                return ResourceManager.GetString("Btn_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Code Library.
        /// </summary>
        public static string Btn_ViewCodeLibrary {
            get {
                return ResourceManager.GetString("Btn_ViewCodeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Config (Legacy).
        /// </summary>
        public static string Calc_Audio {
            get {
                return ResourceManager.GetString("Calc_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear DVD Entertainment.
        /// </summary>
        public static string Calc_Audio_DVD {
            get {
                return ResourceManager.GetString("Calc_Audio_DVD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellite Radio.
        /// </summary>
        public static string Calc_Audio_Sat {
            get {
                return ResourceManager.GetString("Calc_Audio_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audiophile / Subwoofer.
        /// </summary>
        public static string Calc_Audio_Sub {
            get {
                return ResourceManager.GetString("Calc_Audio_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary:.
        /// </summary>
        public static string Calc_Binary {
            get {
                return ResourceManager.GetString("Calc_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum Calculator.
        /// </summary>
        public static string Calc_Checksum {
            get {
                return ResourceManager.GetString("Calc_Checksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checksum:.
        /// </summary>
        public static string Calc_Checksum_Result {
            get {
                return ResourceManager.GetString("Calc_Checksum_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex/Binary Converter.
        /// </summary>
        public static string Calc_Converter {
            get {
                return ResourceManager.GetString("Calc_Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data 1 (hex):.
        /// </summary>
        public static string Calc_Data1 {
            get {
                return ResourceManager.GetString("Calc_Data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data 2 (hex):.
        /// </summary>
        public static string Calc_Data2 {
            get {
                return ResourceManager.GetString("Calc_Data2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data 3 (hex):.
        /// </summary>
        public static string Calc_Data3 {
            get {
                return ResourceManager.GetString("Calc_Data3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex:.
        /// </summary>
        public static string Calc_Hex {
            get {
                return ResourceManager.GetString("Calc_Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module ID (hex):.
        /// </summary>
        public static string Calc_ModuleID {
            get {
                return ResourceManager.GetString("Calc_ModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Calc Checksum (last byte).
        /// </summary>
        public static string Calc_ReCalc {
            get {
                return ResourceManager.GetString("Calc_ReCalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TPMS PSI Calculator.
        /// </summary>
        public static string Calc_TPMS {
            get {
                return ResourceManager.GetString("Calc_TPMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter PSI. Result is Hex value for 726-02-01..
        /// </summary>
        public static string Calc_TPMS_Desc {
            get {
                return ResourceManager.GetString("Calc_TPMS_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN Converter.
        /// </summary>
        public static string Calc_VIN {
            get {
                return ResourceManager.GetString("Calc_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to Hex Blocks.
        /// </summary>
        public static string Calc_VIN_Convert {
            get {
                return ResourceManager.GetString("Calc_VIN_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Checksum bits.
        /// </summary>
        public static string Chk_IncludeChecksum {
            get {
                return ResourceManager.GetString("Chk_IncludeChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Module Names.
        /// </summary>
        public static string Chk_ShowModuleNames {
            get {
                return ResourceManager.GetString("Chk_ShowModuleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Show Non-Matching Groups.
        /// </summary>
        public static string Chk_ShowOnlyMismatches {
            get {
                return ResourceManager.GetString("Chk_ShowOnlyMismatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        public static string Col_Binary {
            get {
                return ResourceManager.GetString("Col_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration.
        /// </summary>
        public static string Col_Calibration {
            get {
                return ResourceManager.GetString("Col_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data1.
        /// </summary>
        public static string Col_Data1 {
            get {
                return ResourceManager.GetString("Col_Data1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data2.
        /// </summary>
        public static string Col_Data2 {
            get {
                return ResourceManager.GetString("Col_Data2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data3.
        /// </summary>
        public static string Col_Data3 {
            get {
                return ResourceManager.GetString("Col_Data3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Col_Date {
            get {
                return ResourceManager.GetString("Col_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known Features.
        /// </summary>
        public static string Col_KnownFeatures {
            get {
                return ResourceManager.GetString("Col_KnownFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        public static string Col_Meaning {
            get {
                return ResourceManager.GetString("Col_Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Col_Model {
            get {
                return ResourceManager.GetString("Col_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Address.
        /// </summary>
        public static string Col_ModuleAddress {
            get {
                return ResourceManager.GetString("Col_ModuleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string Col_ModuleName {
            get {
                return ResourceManager.GetString("Col_ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Col_Name {
            get {
                return ResourceManager.GetString("Col_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Col_Notes {
            get {
                return ResourceManager.GetString("Col_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PartNumber.
        /// </summary>
        public static string Col_PartNumber {
            get {
                return ResourceManager.GetString("Col_PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Col_Position {
            get {
                return ResourceManager.GetString("Col_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same?.
        /// </summary>
        public static string Col_Same {
            get {
                return ResourceManager.GetString("Col_Same", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strategy.
        /// </summary>
        public static string Col_Strategy {
            get {
                return ResourceManager.GetString("Col_Strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Col_Value {
            get {
                return ResourceManager.GetString("Col_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Col_Year {
            get {
                return ResourceManager.GetString("Col_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare CCC bits as well.
        /// </summary>
        public static string Deduce_CompareCCC {
            get {
                return ResourceManager.GetString("Deduce_CompareCCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Deduce_Features {
            get {
                return ResourceManager.GetString("Deduce_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Figure It Out!.
        /// </summary>
        public static string Deduce_FigureItOut {
            get {
                return ResourceManager.GetString("Deduce_FigureItOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Perfect Bits.
        /// </summary>
        public static string Deduce_FindPerfect {
            get {
                return ResourceManager.GetString("Deduce_FindPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load from Database.
        /// </summary>
        public static string Deduce_LoadDB {
            get {
                return ResourceManager.GetString("Deduce_LoadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Options.
        /// </summary>
        public static string Deduce_LoadOptions {
            get {
                return ResourceManager.GetString("Deduce_LoadOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Deduce_Models {
            get {
                return ResourceManager.GetString("Deduce_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Perfect Bits&quot; are listed at the bottom. Bits are numbered from left to right starting at zero..
        /// </summary>
        public static string Deduce_Note_Perfect {
            get {
                return ResourceManager.GetString("Deduce_Note_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or enter VIN:.
        /// </summary>
        public static string Deduce_Or {
            get {
                return ResourceManager.GetString("Deduce_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review results below.
        /// </summary>
        public static string Deduce_Review {
            get {
                return ResourceManager.GetString("Deduce_Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select feature to deduce:.
        /// </summary>
        public static string Deduce_SelectFeat {
            get {
                return ResourceManager.GetString("Deduce_SelectFeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a saved vehicle:.
        /// </summary>
        public static string Deduce_SelectVehicle {
            get {
                return ResourceManager.GetString("Deduce_SelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Years and Models:.
        /// </summary>
        public static string Deduce_SelectYM {
            get {
                return ResourceManager.GetString("Deduce_SelectYM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string Deduce_Years {
            get {
                return ResourceManager.GetString("Deduce_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string DefsDB_Edit {
            get {
                return ResourceManager.GetString("DefsDB_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string DefsDB_Export {
            get {
                return ResourceManager.GetString("DefsDB_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string DefsDB_Import {
            get {
                return ResourceManager.GetString("DefsDB_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definitions Database.
        /// </summary>
        public static string DefsDB_Title {
            get {
                return ResourceManager.GetString("DefsDB_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser &amp; Actions.
        /// </summary>
        public static string Grp_BrowserAct {
            get {
                return ResourceManager.GetString("Grp_BrowserAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Selection.
        /// </summary>
        public static string Grp_VehicleSelection {
            get {
                return ResourceManager.GetString("Grp_VehicleSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As-Built File # 1:.
        /// </summary>
        public static string Lbl_File1 {
            get {
                return ResourceManager.GetString("Lbl_File1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As-Built File # 2:.
        /// </summary>
        public static string Lbl_File2 {
            get {
                return ResourceManager.GetString("Lbl_File2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As-Built File # 3:.
        /// </summary>
        public static string Lbl_File3 {
            get {
                return ResourceManager.GetString("Lbl_File3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As-Built File # 4:.
        /// </summary>
        public static string Lbl_File4 {
            get {
                return ResourceManager.GetString("Lbl_File4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [no file].
        /// </summary>
        public static string Lbl_NoFile {
            get {
                return ResourceManager.GetString("Lbl_NoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary.
        /// </summary>
        public static string Menu_Binary {
            get {
                return ResourceManager.GetString("Menu_Binary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data 1 (hex).
        /// </summary>
        public static string Menu_Data1Hex {
            get {
                return ResourceManager.GetString("Menu_Data1Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data 2 (hex).
        /// </summary>
        public static string Menu_Data2Hex {
            get {
                return ResourceManager.GetString("Menu_Data2Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data 3 (hex).
        /// </summary>
        public static string Menu_Data3Hex {
            get {
                return ResourceManager.GetString("Menu_Data3Hex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode with NHTSA (Online).
        /// </summary>
        public static string Menu_DecodeNHTSA {
            get {
                return ResourceManager.GetString("Menu_DecodeNHTSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File.
        /// </summary>
        public static string Menu_DeleteFile {
            get {
                return ResourceManager.GetString("Menu_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Features.
        /// </summary>
        public static string Menu_EditFeatures {
            get {
                return ResourceManager.GetString("Menu_EditFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entire Line.
        /// </summary>
        public static string Menu_EntireLine {
            get {
                return ResourceManager.GetString("Menu_EntireLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Module.
        /// </summary>
        public static string Menu_ExportModule {
            get {
                return ResourceManager.GetString("Menu_ExportModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identify Feature.
        /// </summary>
        public static string Menu_IdentifyFeature {
            get {
                return ResourceManager.GetString("Menu_IdentifyFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Library.
        /// </summary>
        public static string Menu_ScanLibrary {
            get {
                return ResourceManager.GetString("Menu_ScanLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Compare #1.
        /// </summary>
        public static string Menu_SetAsCompare1 {
            get {
                return ResourceManager.GetString("Menu_SetAsCompare1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Compare #2.
        /// </summary>
        public static string Menu_SetAsCompare2 {
            get {
                return ResourceManager.GetString("Menu_SetAsCompare2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Compare #3.
        /// </summary>
        public static string Menu_SetAsCompare3 {
            get {
                return ResourceManager.GetString("Menu_SetAsCompare3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Compare #4.
        /// </summary>
        public static string Menu_SetAsCompare4 {
            get {
                return ResourceManager.GetString("Menu_SetAsCompare4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To ABT....
        /// </summary>
        public static string Menu_ToABT {
            get {
                return ResourceManager.GetString("Menu_ToABT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To UCDS....
        /// </summary>
        public static string Menu_ToUCDS {
            get {
                return ResourceManager.GetString("Menu_ToUCDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Mod.
        /// </summary>
        public static string Mod_Add {
            get {
                return ResourceManager.GetString("Mod_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        public static string Mod_Export {
            get {
                return ResourceManager.GetString("Mod_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import CSV.
        /// </summary>
        public static string Mod_Import {
            get {
                return ResourceManager.GetString("Mod_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Mods_Category {
            get {
                return ResourceManager.GetString("Mods_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a mod from the list to view details..
        /// </summary>
        public static string Mods_Help {
            get {
                return ResourceManager.GetString("Mods_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Platform:.
        /// </summary>
        public static string Mods_SelectPlatform {
            get {
                return ResourceManager.GetString("Mods_SelectPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Mods_Title {
            get {
                return ResourceManager.GetString("Mods_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext. Browser.
        /// </summary>
        public static string Moto_ExtBrowser {
            get {
                return ResourceManager.GetString("Moto_ExtBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Motorcraft Website &gt;&gt;.
        /// </summary>
        public static string Moto_OpenSite {
            get {
                return ResourceManager.GetString("Moto_OpenSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like the ABT file written out in the &apos;new&apos; 2019-08 ABT format (YES), or the &apos;old&apos; format (NO)?.
        /// </summary>
        public static string Msg_ABTFormatChoice {
            get {
                return ResourceManager.GetString("Msg_ABTFormatChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module data contains sections / blocks with an ID greater than &apos;99&apos;, and therefore requires the ABT file to be written out in the &apos;new&apos; 2019-08 ABT format..
        /// </summary>
        public static string Msg_ABTNewFormat {
            get {
                return ResourceManager.GetString("Msg_ABTNewFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysis is complete..
        /// </summary>
        public static string Msg_AnalysisComplete {
            get {
                return ResourceManager.GetString("Msg_AnalysisComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set clipboard text..
        /// </summary>
        public static string Msg_ClipboardFailed {
            get {
                return ResourceManager.GetString("Msg_ClipboardFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete &apos;{0}&apos;?.
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to COMPLETELY WIPE the vehicle database?
        ///This cannot be undone..
        /// </summary>
        public static string Msg_ConfirmWipe {
            get {
                return ResourceManager.GetString("Msg_ConfirmWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cleared successfully..
        /// </summary>
        public static string Msg_DatabaseCleared {
            get {
                return ResourceManager.GetString("Msg_DatabaseCleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download failed: {0}
        ///Opening browser instead..
        /// </summary>
        public static string Msg_DownloadFailed {
            get {
                return ResourceManager.GetString("Msg_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name for this vehicle..
        /// </summary>
        public static string Msg_EnterVehicleName {
            get {
                return ResourceManager.GetString("Msg_EnterVehicleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting: {0}.
        /// </summary>
        public static string Msg_ErrorExporting {
            get {
                return ResourceManager.GetString("Msg_ErrorExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing: {0}.
        /// </summary>
        public static string Msg_ErrorImporting {
            get {
                return ResourceManager.GetString("Msg_ErrorImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading: {0}.
        /// </summary>
        public static string Msg_ErrorLoading {
            get {
                return ResourceManager.GetString("Msg_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving: {0}.
        /// </summary>
        public static string Msg_ErrorSaving {
            get {
                return ResourceManager.GetString("Msg_ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Successful!.
        /// </summary>
        public static string Msg_ExportSuccessful {
            get {
                return ResourceManager.GetString("Msg_ExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal Application Error: {0}.
        /// </summary>
        public static string Msg_FatalError {
            get {
                return ResourceManager.GetString("Msg_FatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} unique modules..
        /// </summary>
        public static string Msg_FoundModules {
            get {
                return ResourceManager.GetString("Msg_FoundModules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Successful! Database reloaded..
        /// </summary>
        public static string Msg_ImportSuccessful {
            get {
                return ResourceManager.GetString("Msg_ImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} vehicles from database..
        /// </summary>
        public static string Msg_LoadedVehicles {
            get {
                return ResourceManager.GetString("Msg_LoadedVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load file: {0}
        ///File not found or unknown format.
        ///(Check if file was moved or deleted).
        /// </summary>
        public static string Msg_LoadError {
            get {
                return ResourceManager.GetString("Msg_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error migrating CSVs to Database: {0}.
        /// </summary>
        public static string Msg_MigrationError {
            get {
                return ResourceManager.GetString("Msg_MigrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No conclusive bits found. Try selecting more vehicles with diverse feature sets..
        /// </summary>
        public static string Msg_NoConclusiveBits {
            get {
                return ResourceManager.GetString("Msg_NoConclusiveBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No vehicle features found in the database.
        ///
        ///To Auto-Discover Features:
        ///1. Go to the &apos;Vehicle Database&apos; tab.
        ///2. Select your vehicles.
        ///3. Right-Click and choose &apos;Decode with NHTSA (Online)&apos;.
        ///
        ///This will automatically fetch official specs using the government API..
        /// </summary>
        public static string Msg_NoFeaturesFound {
            get {
                return ResourceManager.GetString("Msg_NoFeaturesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file path to save..
        /// </summary>
        public static string Msg_NoFilePath {
            get {
                return ResourceManager.GetString("Msg_NoFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No modules found for the selected vehicles..
        /// </summary>
        public static string Msg_NoModulesFound {
            get {
                return ResourceManager.GetString("Msg_NoModulesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysis is useless because there were no vehicles with this feature..
        /// </summary>
        public static string Msg_NoVehiclesWithFeature {
            get {
                return ResourceManager.GetString("Msg_NoVehiclesWithFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The analysis is useless because there were no vehicles missing this feature..
        /// </summary>
        public static string Msg_NoVehiclesWithoutFeature {
            get {
                return ResourceManager.GetString("Msg_NoVehiclesWithoutFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to set IE11 Emulation Key: {0}.
        /// </summary>
        public static string Msg_RegistryError {
            get {
                return ResourceManager.GetString("Msg_RegistryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a feature to deduce..
        /// </summary>
        public static string Msg_SelectFeature {
            get {
                return ResourceManager.GetString("Msg_SelectFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one vehicle model..
        /// </summary>
        public static string Msg_SelectModel {
            get {
                return ResourceManager.GetString("Msg_SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a module bit to deduce..
        /// </summary>
        public static string Msg_SelectModuleBit {
            get {
                return ResourceManager.GetString("Msg_SelectModuleBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row to edit..
        /// </summary>
        public static string Msg_SelectRowToEdit {
            get {
                return ResourceManager.GetString("Msg_SelectRowToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a vehicle from the list..
        /// </summary>
        public static string Msg_SelectVehicle {
            get {
                return ResourceManager.GetString("Msg_SelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one vehicle year..
        /// </summary>
        public static string Msg_SelectYear {
            get {
                return ResourceManager.GetString("Msg_SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one vehicle year and model..
        /// </summary>
        public static string Msg_SelectYearAndModel {
            get {
                return ResourceManager.GetString("Msg_SelectYearAndModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string Msg_Title_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_Title_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Wipe.
        /// </summary>
        public static string Msg_Title_ConfirmWipe {
            get {
                return ResourceManager.GetString("Msg_Title_ConfirmWipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsBuiltExplorer Crash.
        /// </summary>
        public static string Msg_Title_Crash {
            get {
                return ResourceManager.GetString("Msg_Title_Crash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Format.
        /// </summary>
        public static string Msg_Title_ExportFormat {
            get {
                return ResourceManager.GetString("Msg_Title_ExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Msg_Title_Information {
            get {
                return ResourceManager.GetString("Msg_Title_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Error.
        /// </summary>
        public static string Msg_Title_LoadError {
            get {
                return ResourceManager.GetString("Msg_Title_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Name.
        /// </summary>
        public static string Msg_Title_MissingName {
            get {
                return ResourceManager.GetString("Msg_Title_MissingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Path.
        /// </summary>
        public static string Msg_Title_MissingPath {
            get {
                return ResourceManager.GetString("Msg_Title_MissingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Features Found.
        /// </summary>
        public static string Msg_Title_NoFeaturesFound {
            get {
                return ResourceManager.GetString("Msg_Title_NoFeaturesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selection.
        /// </summary>
        public static string Msg_Title_NoSelection {
            get {
                return ResourceManager.GetString("Msg_Title_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Error.
        /// </summary>
        public static string Msg_Title_RegistryError {
            get {
                return ResourceManager.GetString("Msg_Title_RegistryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Msg_Title_Success {
            get {
                return ResourceManager.GetString("Msg_Title_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Error.
        /// </summary>
        public static string Msg_Title_UpdateError {
            get {
                return ResourceManager.GetString("Msg_Title_UpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up to Date.
        /// </summary>
        public static string Msg_Title_UpToDate {
            get {
                return ResourceManager.GetString("Msg_Title_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version..
        /// </summary>
        public static string Msg_UpToDate {
            get {
                return ResourceManager.GetString("Msg_UpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Settings_Appearance {
            get {
                return ResourceManager.GetString("Settings_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup.
        /// </summary>
        public static string Settings_CheckUpdatesOnStartup {
            get {
                return ResourceManager.GetString("Settings_CheckUpdatesOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        public static string Settings_DarkMode {
            get {
                return ResourceManager.GetString("Settings_DarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Management.
        /// </summary>
        public static string Settings_DataManagement {
            get {
                return ResourceManager.GetString("Settings_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Mode.
        /// </summary>
        public static string Settings_LightMode {
            get {
                return ResourceManager.GetString("Settings_LightMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed. Please restart the application to apply changes fully..
        /// </summary>
        public static string Settings_RestartRequired {
            get {
                return ResourceManager.GetString("Settings_RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language:.
        /// </summary>
        public static string Settings_SelectLanguage {
            get {
                return ResourceManager.GetString("Settings_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored Vehicles: {0}.
        /// </summary>
        public static string Settings_StoredVehicles {
            get {
                return ResourceManager.GetString("Settings_StoredVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        public static string Settings_Updates {
            get {
                return ResourceManager.GetString("Settings_Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string Settings_Version {
            get {
                return ResourceManager.GetString("Settings_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Tab_About {
            get {
                return ResourceManager.GetString("Tab_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit Deducer.
        /// </summary>
        public static string Tab_BitDeducer {
            get {
                return ResourceManager.GetString("Tab_BitDeducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Database.
        /// </summary>
        public static string Tab_Browse {
            get {
                return ResourceManager.GetString("Tab_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculators &amp; Tools.
        /// </summary>
        public static string Tab_Calculators {
            get {
                return ResourceManager.GetString("Tab_Calculators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare As-Built.
        /// </summary>
        public static string Tab_Compare {
            get {
                return ResourceManager.GetString("Tab_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN Decoder.
        /// </summary>
        public static string Tab_Decode {
            get {
                return ResourceManager.GetString("Tab_Decode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Deducer.
        /// </summary>
        public static string Tab_Deducer {
            get {
                return ResourceManager.GetString("Tab_Deducer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deducer (Advanced).
        /// </summary>
        public static string Tab_DeducerAdvanced {
            get {
                return ResourceManager.GetString("Tab_DeducerAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Tab_Help {
            get {
                return ResourceManager.GetString("Tab_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Mods.
        /// </summary>
        public static string Tab_Mods {
            get {
                return ResourceManager.GetString("Tab_Mods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MotorCraft AsBuilt Data.
        /// </summary>
        public static string Tab_MotorCraft {
            get {
                return ResourceManager.GetString("Tab_MotorCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog:.
        /// </summary>
        public static string Update_Changelog {
            get {
                return ResourceManager.GetString("Update_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        public static string Update_CurrentVersion {
            get {
                return ResourceManager.GetString("Update_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available: {0}.
        /// </summary>
        public static string Update_NewVersion {
            get {
                return ResourceManager.GetString("Update_NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string Update_Title {
            get {
                return ResourceManager.GetString("Update_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features:.
        /// </summary>
        public static string VehicleDB_Features {
            get {
                return ResourceManager.GetString("VehicleDB_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Name:.
        /// </summary>
        public static string VehicleDB_Name {
            get {
                return ResourceManager.GetString("VehicleDB_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Database.
        /// </summary>
        public static string VehicleDB_Title {
            get {
                return ResourceManager.GetString("VehicleDB_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN:.
        /// </summary>
        public static string VehicleDB_VIN {
            get {
                return ResourceManager.GetString("VehicleDB_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter VIN:.
        /// </summary>
        public static string VIN_Input {
            get {
                return ResourceManager.GetString("VIN_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or select a saved vehicle:.
        /// </summary>
        public static string VIN_SelectVehicle {
            get {
                return ResourceManager.GetString("VIN_SelectVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use NHTSA Online Decoder.
        /// </summary>
        public static string VIN_UseNHTSA {
            get {
                return ResourceManager.GetString("VIN_UseNHTSA", resourceCulture);
            }
        }
    }
}
