//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsBuiltExplorer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsBuiltExplorer.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // ===== TAB NAMES =====
        
        public static string Tab_Compare => ResourceManager.GetString("Tab_Compare", resourceCulture);
        public static string Tab_Calculators => ResourceManager.GetString("Tab_Calculators", resourceCulture);
        public static string Tab_Deducer => ResourceManager.GetString("Tab_Deducer", resourceCulture);
        public static string Tab_DeducerAdvanced => ResourceManager.GetString("Tab_DeducerAdvanced", resourceCulture);
        public static string Tab_Mods => ResourceManager.GetString("Tab_Mods", resourceCulture);
        public static string Tab_BitDeducer => ResourceManager.GetString("Tab_BitDeducer", resourceCulture);
        public static string Tab_Browse => ResourceManager.GetString("Tab_Browse", resourceCulture);
        public static string Tab_Decode => ResourceManager.GetString("Tab_Decode", resourceCulture);
        public static string Tab_Help => ResourceManager.GetString("Tab_Help", resourceCulture);
        public static string Tab_About => ResourceManager.GetString("Tab_About", resourceCulture);
        
        // ===== BUTTONS =====
        
        public static string Btn_Browse => ResourceManager.GetString("Btn_Browse", resourceCulture);
        public static string Btn_Load => ResourceManager.GetString("Btn_Load", resourceCulture);
        public static string Btn_Save => ResourceManager.GetString("Btn_Save", resourceCulture);
        public static string Btn_Cancel => ResourceManager.GetString("Btn_Cancel", resourceCulture);
        public static string Btn_ViewCodeLibrary => ResourceManager.GetString("Btn_ViewCodeLibrary", resourceCulture);
        public static string Btn_CheckNow => ResourceManager.GetString("Btn_CheckNow", resourceCulture);
        public static string Btn_Checking => ResourceManager.GetString("Btn_Checking", resourceCulture);
        public static string Btn_ClearDatabase => ResourceManager.GetString("Btn_ClearDatabase", resourceCulture);
        public static string Btn_Refresh => ResourceManager.GetString("Btn_Refresh", resourceCulture);
        public static string Btn_Scan => ResourceManager.GetString("Btn_Scan", resourceCulture);
        public static string Btn_Decode => ResourceManager.GetString("Btn_Decode", resourceCulture);
        public static string Btn_Go => ResourceManager.GetString("Btn_Go", resourceCulture);
        public static string Btn_OpenExternal => ResourceManager.GetString("Btn_OpenExternal", resourceCulture);
        public static string Btn_Convert => ResourceManager.GetString("Btn_Convert", resourceCulture);
        public static string Btn_Calculate => ResourceManager.GetString("Btn_Calculate", resourceCulture);
        public static string Btn_DownloadNow => ResourceManager.GetString("Btn_DownloadNow", resourceCulture);
        public static string Btn_Skip => ResourceManager.GetString("Btn_Skip", resourceCulture);
        public static string Btn_RemindLater => ResourceManager.GetString("Btn_RemindLater", resourceCulture);
        
        // ===== LABELS =====
        
        public static string Lbl_File1 => ResourceManager.GetString("Lbl_File1", resourceCulture);
        public static string Lbl_File2 => ResourceManager.GetString("Lbl_File2", resourceCulture);
        public static string Lbl_File3 => ResourceManager.GetString("Lbl_File3", resourceCulture);
        public static string Lbl_File4 => ResourceManager.GetString("Lbl_File4", resourceCulture);
        public static string Lbl_NoFile => ResourceManager.GetString("Lbl_NoFile", resourceCulture);
        public static string Chk_IncludeChecksum => ResourceManager.GetString("Chk_IncludeChecksum", resourceCulture);
        public static string Chk_ShowModuleNames => ResourceManager.GetString("Chk_ShowModuleNames", resourceCulture);
        public static string Chk_ShowOnlyMismatches => ResourceManager.GetString("Chk_ShowOnlyMismatches", resourceCulture);
        
        // ===== COLUMN HEADERS =====
        
        public static string Col_ModuleAddress => ResourceManager.GetString("Col_ModuleAddress", resourceCulture);
        public static string Col_ModuleName => ResourceManager.GetString("Col_ModuleName", resourceCulture);
        public static string Col_Data1 => ResourceManager.GetString("Col_Data1", resourceCulture);
        public static string Col_Data2 => ResourceManager.GetString("Col_Data2", resourceCulture);
        public static string Col_Data3 => ResourceManager.GetString("Col_Data3", resourceCulture);
        public static string Col_Same => ResourceManager.GetString("Col_Same", resourceCulture);
        public static string Col_Binary => ResourceManager.GetString("Col_Binary", resourceCulture);
        public static string Col_KnownFeatures => ResourceManager.GetString("Col_KnownFeatures", resourceCulture);
        public static string Col_PartNumber => ResourceManager.GetString("Col_PartNumber", resourceCulture);
        public static string Col_Strategy => ResourceManager.GetString("Col_Strategy", resourceCulture);
        public static string Col_Calibration => ResourceManager.GetString("Col_Calibration", resourceCulture);
        public static string Col_Position => ResourceManager.GetString("Col_Position", resourceCulture);
        public static string Col_Value => ResourceManager.GetString("Col_Value", resourceCulture);
        public static string Col_Meaning => ResourceManager.GetString("Col_Meaning", resourceCulture);
        public static string Col_Notes => ResourceManager.GetString("Col_Notes", resourceCulture);
        
        // ===== CONTEXT MENU =====
        
        public static string Menu_Copy => ResourceManager.GetString("Menu_Copy", resourceCulture);
        public static string Menu_EntireLine => ResourceManager.GetString("Menu_EntireLine", resourceCulture);
        public static string Menu_Data1Hex => ResourceManager.GetString("Menu_Data1Hex", resourceCulture);
        public static string Menu_Data2Hex => ResourceManager.GetString("Menu_Data2Hex", resourceCulture);
        public static string Menu_Data3Hex => ResourceManager.GetString("Menu_Data3Hex", resourceCulture);
        public static string Menu_Binary => ResourceManager.GetString("Menu_Binary", resourceCulture);
        public static string Menu_ExportModule => ResourceManager.GetString("Menu_ExportModule", resourceCulture);
        public static string Menu_ToUCDS => ResourceManager.GetString("Menu_ToUCDS", resourceCulture);
        public static string Menu_ToABT => ResourceManager.GetString("Menu_ToABT", resourceCulture);
        public static string Menu_IdentifyFeature => ResourceManager.GetString("Menu_IdentifyFeature", resourceCulture);
        public static string Menu_SetAsCompare1 => ResourceManager.GetString("Menu_SetAsCompare1", resourceCulture);
        public static string Menu_SetAsCompare2 => ResourceManager.GetString("Menu_SetAsCompare2", resourceCulture);
        public static string Menu_SetAsCompare3 => ResourceManager.GetString("Menu_SetAsCompare3", resourceCulture);
        public static string Menu_SetAsCompare4 => ResourceManager.GetString("Menu_SetAsCompare4", resourceCulture);
        public static string Menu_EditFeatures => ResourceManager.GetString("Menu_EditFeatures", resourceCulture);
        public static string Menu_DecodeNHTSA => ResourceManager.GetString("Menu_DecodeNHTSA", resourceCulture);
        public static string Menu_ScanLibrary => ResourceManager.GetString("Menu_ScanLibrary", resourceCulture);
        public static string Menu_DeleteFile => ResourceManager.GetString("Menu_DeleteFile", resourceCulture);
        
        // ===== SETTINGS =====
        
        public static string Settings_Title => ResourceManager.GetString("Settings_Title", resourceCulture);
        public static string Settings_Appearance => ResourceManager.GetString("Settings_Appearance", resourceCulture);
        public static string Settings_LightMode => ResourceManager.GetString("Settings_LightMode", resourceCulture);
        public static string Settings_DarkMode => ResourceManager.GetString("Settings_DarkMode", resourceCulture);
        public static string Settings_DataManagement => ResourceManager.GetString("Settings_DataManagement", resourceCulture);
        public static string Settings_StoredVehicles => ResourceManager.GetString("Settings_StoredVehicles", resourceCulture);
        public static string Settings_Updates => ResourceManager.GetString("Settings_Updates", resourceCulture);
        public static string Settings_CheckUpdatesOnStartup => ResourceManager.GetString("Settings_CheckUpdatesOnStartup", resourceCulture);
        public static string Settings_Version => ResourceManager.GetString("Settings_Version", resourceCulture);
        public static string Settings_Language => ResourceManager.GetString("Settings_Language", resourceCulture);
        public static string Settings_SelectLanguage => ResourceManager.GetString("Settings_SelectLanguage", resourceCulture);
        public static string Settings_RestartRequired => ResourceManager.GetString("Settings_RestartRequired", resourceCulture);
        
        // ===== CALCULATORS =====
        
        public static string Calc_Checksum => ResourceManager.GetString("Calc_Checksum", resourceCulture);
        public static string Calc_ModuleID => ResourceManager.GetString("Calc_ModuleID", resourceCulture);
        public static string Calc_Data1 => ResourceManager.GetString("Calc_Data1", resourceCulture);
        public static string Calc_Data2 => ResourceManager.GetString("Calc_Data2", resourceCulture);
        public static string Calc_Data3 => ResourceManager.GetString("Calc_Data3", resourceCulture);
        public static string Calc_Checksum_Result => ResourceManager.GetString("Calc_Checksum_Result", resourceCulture);
        public static string Calc_Converter => ResourceManager.GetString("Calc_Converter", resourceCulture);
        public static string Calc_Hex => ResourceManager.GetString("Calc_Hex", resourceCulture);
        public static string Calc_Binary => ResourceManager.GetString("Calc_Binary", resourceCulture);
        public static string Calc_TPMS => ResourceManager.GetString("Calc_TPMS", resourceCulture);
        public static string Calc_VIN => ResourceManager.GetString("Calc_VIN", resourceCulture);
        public static string Calc_Audio => ResourceManager.GetString("Calc_Audio", resourceCulture);
        
        // ===== DEDUCER =====
        
        public static string Deduce_SelectVehicle => ResourceManager.GetString("Deduce_SelectVehicle", resourceCulture);
        public static string Deduce_Or => ResourceManager.GetString("Deduce_Or", resourceCulture);
        public static string Deduce_Models => ResourceManager.GetString("Deduce_Models", resourceCulture);
        public static string Deduce_Years => ResourceManager.GetString("Deduce_Years", resourceCulture);
        public static string Deduce_Features => ResourceManager.GetString("Deduce_Features", resourceCulture);
        public static string Deduce_FigureItOut => ResourceManager.GetString("Deduce_FigureItOut", resourceCulture);
        public static string Deduce_LoadOptions => ResourceManager.GetString("Deduce_LoadOptions", resourceCulture);
        
        // ===== MODS =====
        
        public static string Mods_SelectPlatform => ResourceManager.GetString("Mods_SelectPlatform", resourceCulture);
        public static string Mods_Help => ResourceManager.GetString("Mods_Help", resourceCulture);
        public static string Mods_Title => ResourceManager.GetString("Mods_Title", resourceCulture);
        public static string Mods_Category => ResourceManager.GetString("Mods_Category", resourceCulture);
        
        // ===== VIN DECODER =====
        
        public static string VIN_Input => ResourceManager.GetString("VIN_Input", resourceCulture);
        public static string VIN_SelectVehicle => ResourceManager.GetString("VIN_SelectVehicle", resourceCulture);
        public static string VIN_UseNHTSA => ResourceManager.GetString("VIN_UseNHTSA", resourceCulture);
        
        // ===== MESSAGE BOXES =====
        
        public static string Msg_LoadError => ResourceManager.GetString("Msg_LoadError", resourceCulture);
        public static string Msg_Title_LoadError => ResourceManager.GetString("Msg_Title_LoadError", resourceCulture);
        public static string Msg_ConfirmWipe => ResourceManager.GetString("Msg_ConfirmWipe", resourceCulture);
        public static string Msg_Title_ConfirmWipe => ResourceManager.GetString("Msg_Title_ConfirmWipe", resourceCulture);
        public static string Msg_DatabaseCleared => ResourceManager.GetString("Msg_DatabaseCleared", resourceCulture);
        public static string Msg_Title_Success => ResourceManager.GetString("Msg_Title_Success", resourceCulture);
        public static string Msg_UpToDate => ResourceManager.GetString("Msg_UpToDate", resourceCulture);
        public static string Msg_Title_UpToDate => ResourceManager.GetString("Msg_Title_UpToDate", resourceCulture);
        public static string Msg_EnterVehicleName => ResourceManager.GetString("Msg_EnterVehicleName", resourceCulture);
        public static string Msg_Title_MissingName => ResourceManager.GetString("Msg_Title_MissingName", resourceCulture);
        public static string Msg_NoFilePath => ResourceManager.GetString("Msg_NoFilePath", resourceCulture);
        public static string Msg_Title_MissingPath => ResourceManager.GetString("Msg_Title_MissingPath", resourceCulture);
        public static string Msg_ConfirmDelete => ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
        public static string Msg_Title_ConfirmDelete => ResourceManager.GetString("Msg_Title_ConfirmDelete", resourceCulture);
        public static string Msg_SelectVehicle => ResourceManager.GetString("Msg_SelectVehicle", resourceCulture);
        public static string Msg_Title_NoSelection => ResourceManager.GetString("Msg_Title_NoSelection", resourceCulture);
        public static string Msg_DownloadFailed => ResourceManager.GetString("Msg_DownloadFailed", resourceCulture);
        public static string Msg_Title_UpdateError => ResourceManager.GetString("Msg_Title_UpdateError", resourceCulture);
        public static string Msg_ErrorLoading => ResourceManager.GetString("Msg_ErrorLoading", resourceCulture);
        public static string Msg_SelectRowToEdit => ResourceManager.GetString("Msg_SelectRowToEdit", resourceCulture);
        public static string Msg_ErrorSaving => ResourceManager.GetString("Msg_ErrorSaving", resourceCulture);
        public static string Msg_ExportSuccessful => ResourceManager.GetString("Msg_ExportSuccessful", resourceCulture);
        public static string Msg_ErrorExporting => ResourceManager.GetString("Msg_ErrorExporting", resourceCulture);
        public static string Msg_ImportSuccessful => ResourceManager.GetString("Msg_ImportSuccessful", resourceCulture);
        public static string Msg_ErrorImporting => ResourceManager.GetString("Msg_ErrorImporting", resourceCulture);
        public static string Msg_SelectFeature => ResourceManager.GetString("Msg_SelectFeature", resourceCulture);
        public static string Msg_SelectModel => ResourceManager.GetString("Msg_SelectModel", resourceCulture);
        public static string Msg_SelectYear => ResourceManager.GetString("Msg_SelectYear", resourceCulture);
        public static string Msg_SelectYearAndModel => ResourceManager.GetString("Msg_SelectYearAndModel", resourceCulture);
        public static string Msg_NoFeaturesFound => ResourceManager.GetString("Msg_NoFeaturesFound", resourceCulture);
        public static string Msg_Title_NoFeaturesFound => ResourceManager.GetString("Msg_Title_NoFeaturesFound", resourceCulture);
        public static string Msg_NoVehiclesWithFeature => ResourceManager.GetString("Msg_NoVehiclesWithFeature", resourceCulture);
        public static string Msg_NoVehiclesWithoutFeature => ResourceManager.GetString("Msg_NoVehiclesWithoutFeature", resourceCulture);
        public static string Msg_AnalysisComplete => ResourceManager.GetString("Msg_AnalysisComplete", resourceCulture);
        public static string Msg_SelectModuleBit => ResourceManager.GetString("Msg_SelectModuleBit", resourceCulture);
        public static string Msg_LoadedVehicles => ResourceManager.GetString("Msg_LoadedVehicles", resourceCulture);
        public static string Msg_NoModulesFound => ResourceManager.GetString("Msg_NoModulesFound", resourceCulture);
        public static string Msg_FoundModules => ResourceManager.GetString("Msg_FoundModules", resourceCulture);
        public static string Msg_ClipboardFailed => ResourceManager.GetString("Msg_ClipboardFailed", resourceCulture);
        public static string Msg_ABTNewFormat => ResourceManager.GetString("Msg_ABTNewFormat", resourceCulture);
        public static string Msg_Title_Information => ResourceManager.GetString("Msg_Title_Information", resourceCulture);
        public static string Msg_ABTFormatChoice => ResourceManager.GetString("Msg_ABTFormatChoice", resourceCulture);
        public static string Msg_Title_ExportFormat => ResourceManager.GetString("Msg_Title_ExportFormat", resourceCulture);
        public static string Msg_NoConclusiveBits => ResourceManager.GetString("Msg_NoConclusiveBits", resourceCulture);
        public static string Msg_FatalError => ResourceManager.GetString("Msg_FatalError", resourceCulture);
        public static string Msg_Title_Crash => ResourceManager.GetString("Msg_Title_Crash", resourceCulture);
        public static string Msg_RegistryError => ResourceManager.GetString("Msg_RegistryError", resourceCulture);
        public static string Msg_Title_RegistryError => ResourceManager.GetString("Msg_Title_RegistryError", resourceCulture);
        public static string Msg_MigrationError => ResourceManager.GetString("Msg_MigrationError", resourceCulture);
        
        // ===== UPDATE DIALOG =====
        
        public static string Update_Title => ResourceManager.GetString("Update_Title", resourceCulture);
        public static string Update_NewVersion => ResourceManager.GetString("Update_NewVersion", resourceCulture);
        public static string Update_CurrentVersion => ResourceManager.GetString("Update_CurrentVersion", resourceCulture);
        public static string Update_Changelog => ResourceManager.GetString("Update_Changelog", resourceCulture);
        
        // ===== ABOUT =====
        
        public static string About_Title => ResourceManager.GetString("About_Title", resourceCulture);
        public static string About_Developer => ResourceManager.GetString("About_Developer", resourceCulture);
        public static string About_Credits => ResourceManager.GetString("About_Credits", resourceCulture);
        public static string About_GitHub => ResourceManager.GetString("About_GitHub", resourceCulture);
        
        // ===== VEHICLE DB =====
        
        public static string VehicleDB_Title => ResourceManager.GetString("VehicleDB_Title", resourceCulture);
        public static string VehicleDB_Name => ResourceManager.GetString("VehicleDB_Name", resourceCulture);
        public static string VehicleDB_VIN => ResourceManager.GetString("VehicleDB_VIN", resourceCulture);
        public static string VehicleDB_Features => ResourceManager.GetString("VehicleDB_Features", resourceCulture);
        
        // ===== DEFINITIONS DB =====
        
        public static string DefsDB_Title => ResourceManager.GetString("DefsDB_Title", resourceCulture);
        public static string DefsDB_Export => ResourceManager.GetString("DefsDB_Export", resourceCulture);
        public static string DefsDB_Import => ResourceManager.GetString("DefsDB_Import", resourceCulture);
        public static string DefsDB_Edit => ResourceManager.GetString("DefsDB_Edit", resourceCulture);
    }
}
